import type { Kde, CteUsage, ImportPreviewRow } from "./types";

export const kdeLibrary: Kde[] = [
    {
        code: "HARVEST_DATE",
        name: "Ngày thu hoạch",
        status: "published",
        current_version: "v2",
        nhom_nganh_hang: "Nông sản",
        versions: [
            {
                version: "v2",
                nghi_dinh: "NĐ 37/2025",
                nghi_dinh_full: "37/2025/NĐ-CP",
                co_quan: "Chính phủ",
                import_date: "15/03/2026",
                description: "Ngày thực hiện thu hoạch sản phẩm tại vùng trồng",
                data_type: "date",
                unit: "—",
                validation_rule: "Không được sau ngày hiện tại",
                is_current: true,
            },
            {
                version: "v1",
                nghi_dinh: "NĐ 12/2023",
                nghi_dinh_full: "12/2023/NĐ-CP",
                co_quan: "Chính phủ",
                import_date: "10/01/2023",
                description: "Ngày thu hoạch sản phẩm",
                data_type: "date",
                unit: "—",
                validation_rule: "Không rỗng",
                is_current: false,
            },
        ],
    },
    {
        code: "LOT_NUMBER",
        name: "Số lô sản xuất",
        status: "published",
        current_version: "v1",
        nhom_nganh_hang: "Chung",
        versions: [
            {
                version: "v1",
                nghi_dinh: "NĐ 12/2023",
                nghi_dinh_full: "12/2023/NĐ-CP",
                co_quan: "Chính phủ",
                import_date: "10/01/2023",
                description: "Mã định danh lô sản xuất do nhà máy cấp",
                data_type: "text",
                unit: "—",
                validation_rule: "Tối đa 50 ký tự, không dấu",
                is_current: true,
            },
        ],
    },
    {
        code: "PRODUCER_ID",
        name: "Mã nhà sản xuất",
        status: "published",
        current_version: "v2",
        nhom_nganh_hang: "Chung",
        versions: [
            {
                version: "v2",
                nghi_dinh: "NĐ 37/2025",
                nghi_dinh_full: "37/2025/NĐ-CP",
                co_quan: "Chính phủ",
                import_date: "15/03/2026",
                description: "Mã định danh doanh nghiệp sản xuất trong hệ thống quốc gia",
                data_type: "text",
                unit: "—",
                validation_rule: "Bắt buộc, đúng định dạng MST",
                is_current: true,
            },
            {
                version: "v1",
                nghi_dinh: "NĐ 12/2023",
                nghi_dinh_full: "12/2023/NĐ-CP",
                co_quan: "Chính phủ",
                import_date: "10/01/2023",
                description: "Mã định danh doanh nghiệp sản xuất",
                data_type: "text",
                unit: "—",
                validation_rule: "Bắt buộc",
                is_current: false,
            },
        ],
    },
    {
        code: "WEIGHT_NET",
        name: "Khối lượng tịnh",
        status: "published",
        current_version: "v1",
        nhom_nganh_hang: "Chung",
        versions: [
            {
                version: "v1",
                nghi_dinh: "NĐ 12/2023",
                nghi_dinh_full: "12/2023/NĐ-CP",
                co_quan: "Chính phủ",
                import_date: "10/01/2023",
                description: "Khối lượng thực phẩm không bao bì",
                data_type: "number",
                unit: "kg",
                validation_rule: "> 0, tối đa 4 chữ số thập phân",
                is_current: true,
            },
        ],
    },
    {
        code: "STORAGE_METHOD",
        name: "Phương thức bảo quản",
        status: "published",
        current_version: "v2",
        nhom_nganh_hang: "Chung",
        versions: [
            {
                version: "v2",
                nghi_dinh: "NĐ 37/2025",
                nghi_dinh_full: "37/2025/NĐ-CP",
                co_quan: "Chính phủ",
                import_date: "15/03/2026",
                description: "Phương pháp bảo quản sản phẩm trong chuỗi cung ứng",
                data_type: "enum",
                unit: "—",
                validation_rule: "Chọn từ danh sách",
                enum_options: ["FRESH", "FROZEN", "DRY", "CHILLED", "AMBIENT"],
                is_current: true,
            },
            {
                version: "v1",
                nghi_dinh: "NĐ 12/2023",
                nghi_dinh_full: "12/2023/NĐ-CP",
                co_quan: "Chính phủ",
                import_date: "10/01/2023",
                description: "Phương pháp bảo quản",
                data_type: "enum",
                unit: "—",
                validation_rule: "Chọn từ danh sách",
                enum_options: ["FRESH", "FROZEN", "DRY"],
                is_current: false,
            },
        ],
    },
    {
        code: "EXPIRY_DATE",
        name: "Ngày hết hạn sử dụng",
        status: "published",
        current_version: "v1",
        nhom_nganh_hang: "Chung",
        versions: [
            {
                version: "v1",
                nghi_dinh: "NĐ 12/2023",
                nghi_dinh_full: "12/2023/NĐ-CP",
                co_quan: "Chính phủ",
                import_date: "10/01/2023",
                description: "Ngày sản phẩm hết hạn sử dụng ghi trên bao bì",
                data_type: "date",
                unit: "—",
                validation_rule: "Phải sau ngày sản xuất",
                is_current: true,
            },
        ],
    },
    {
        code: "GPS_LOCATION",
        name: "Tọa độ địa lý",
        status: "published",
        current_version: "v2",
        nhom_nganh_hang: "Chung",
        versions: [
            {
                version: "v2",
                nghi_dinh: "NĐ 37/2025",
                nghi_dinh_full: "37/2025/NĐ-CP",
                co_quan: "Chính phủ",
                import_date: "15/03/2026",
                description: "Vị trí GPS tại thời điểm khai báo sự kiện",
                data_type: "gps",
                unit: "lat/lng",
                validation_rule: "WGS84, độ chính xác ±10m",
                is_current: true,
            },
            {
                version: "v1",
                nghi_dinh: "NĐ 12/2023",
                nghi_dinh_full: "12/2023/NĐ-CP",
                co_quan: "Chính phủ",
                import_date: "10/01/2023",
                description: "Vị trí GPS",
                data_type: "gps",
                unit: "lat/lng",
                validation_rule: "WGS84",
                is_current: false,
            },
        ],
    },
    {
        code: "CERTIFICATE_NO",
        name: "Số giấy chứng nhận",
        status: "deprecated",
        current_version: "v1",
        nhom_nganh_hang: "Chung",
        versions: [
            {
                version: "v1",
                nghi_dinh: "NĐ 12/2023",
                nghi_dinh_full: "12/2023/NĐ-CP",
                co_quan: "Chính phủ",
                import_date: "10/01/2023",
                description: "[Deprecated] Đã tách thành VC riêng trong hệ thống",
                data_type: "text",
                unit: "—",
                validation_rule: "—",
                is_current: true,
            },
        ],
    },
    {
        code: "TEMPERATURE",
        name: "Nhiệt độ vận chuyển",
        status: "published",
        current_version: "v1",
        nhom_nganh_hang: "Chuỗi lạnh",
        versions: [
            {
                version: "v1",
                nghi_dinh: "NĐ 12/2023",
                nghi_dinh_full: "12/2023/NĐ-CP",
                co_quan: "Chính phủ",
                import_date: "10/01/2023",
                description: "Nhiệt độ môi trường trong quá trình vận chuyển",
                data_type: "number",
                unit: "°C",
                validation_rule: "Từ -30 đến 50",
                is_current: true,
            },
        ],
    },
    {
        code: "BATCH_CODE",
        name: "Mã lô hàng",
        status: "published",
        current_version: "v1",
        nhom_nganh_hang: "Chung",
        versions: [
            {
                version: "v1",
                nghi_dinh: "NĐ 37/2025",
                nghi_dinh_full: "37/2025/NĐ-CP",
                co_quan: "Chính phủ",
                import_date: "15/03/2026",
                description: "Mã định danh lô hàng phục vụ truy xuất",
                data_type: "text",
                unit: "—",
                validation_rule: "Không rỗng, tối đa 30 ký tự",
                is_current: true,
            },
        ],
    },
    {
        code: "STORAGE_TEMP",
        name: "Nhiệt độ bảo quản",
        status: "published",
        current_version: "v1",
        nhom_nganh_hang: "Chuỗi lạnh",
        versions: [
            {
                version: "v1",
                nghi_dinh: "NĐ 37/2025",
                nghi_dinh_full: "37/2025/NĐ-CP",
                co_quan: "Chính phủ",
                import_date: "15/03/2026",
                description: "Nhiệt độ bảo quản sản phẩm tại kho",
                data_type: "number",
                unit: "°C",
                validation_rule: "Từ -30 đến 30",
                is_current: true,
            },
        ],
    },
    {
        code: "ORGANIC_CERT",
        name: "Giấy chứng nhận hữu cơ",
        status: "draft",
        current_version: "v1",
        nhom_nganh_hang: "Nông sản",
        versions: [
            {
                version: "v1",
                nghi_dinh: "NĐ 37/2025 (dự thảo)",
                nghi_dinh_full: "37/2025/NĐ-CP",
                co_quan: "Bộ NN&PTNT",
                import_date: "01/04/2026",
                description: "File scan giấy chứng nhận hữu cơ (PDF)",
                data_type: "file",
                unit: "—",
                validation_rule: "PDF, tối đa 5MB",
                is_current: true,
            },
        ],
    },
];

export const cteUsage: CteUsage[] = [
    { kde_code: "HARVEST_DATE", cte_id: "CTE-001", cte_name: "CTE Sản xuất — Nhóm Sữa", layer: "Layer 2", owner: "Bộ Y tế", used_version: "v2", cte_status: "active" },
    { kde_code: "HARVEST_DATE", cte_id: "CTE-002", cte_name: "CTE Thu hoạch — Nhóm Rau củ", layer: "Layer 2", owner: "Bộ NN&PTNT", used_version: "v2", cte_status: "active" },
    { kde_code: "HARVEST_DATE", cte_id: "CTE-003", cte_name: "CTE Trồng trọt — Nhóm Cà phê", layer: "Layer 2", owner: "Sở NNPTNT Đắk Lắk", used_version: "v1", cte_status: "active" },
    { kde_code: "LOT_NUMBER", cte_id: "CTE-004", cte_name: "CTE Đóng gói — Nhóm Thủy sản", layer: "Layer 2", owner: "Bộ NN&PTNT", used_version: "v1", cte_status: "active" },
    { kde_code: "LOT_NUMBER", cte_id: "CTE-005", cte_name: "CTE Chế biến — Nhóm Sữa", layer: "Layer 2", owner: "Bộ Y tế", used_version: "v1", cte_status: "active" },
    { kde_code: "PRODUCER_ID", cte_id: "CTE-006", cte_name: "CTE Sản xuất — Nhóm Sữa", layer: "Layer 2", owner: "Bộ Y tế", used_version: "v2", cte_status: "active" },
    { kde_code: "PRODUCER_ID", cte_id: "CTE-007", cte_name: "CTE Xuất khẩu — Lúa gạo", layer: "Layer 2", owner: "Bộ Công Thương", used_version: "v1", cte_status: "active" },
    { kde_code: "STORAGE_METHOD", cte_id: "CTE-008", cte_name: "CTE Vận chuyển lạnh — Thủy sản", layer: "Layer 2", owner: "Bộ NN&PTNT", used_version: "v2", cte_status: "active" },
    { kde_code: "STORAGE_METHOD", cte_id: "CTE-009", cte_name: "CTE Lưu kho — Nhóm Rau củ", layer: "Layer 2", owner: "Sở NN Hà Nội", used_version: "v1", cte_status: "active" },
    { kde_code: "GPS_LOCATION", cte_id: "CTE-010", cte_name: "CTE Thu hoạch — Nhóm Rau củ", layer: "Layer 2", owner: "Bộ NN&PTNT", used_version: "v2", cte_status: "active" },
    { kde_code: "WEIGHT_NET", cte_id: "CTE-011", cte_name: "CTE Đóng gói — Nhóm Thủy sản", layer: "Layer 2", owner: "Bộ NN&PTNT", used_version: "v1", cte_status: "active" },
    { kde_code: "EXPIRY_DATE", cte_id: "CTE-012", cte_name: "CTE Chế biến — Nhóm Sữa", layer: "Layer 2", owner: "Bộ Y tế", used_version: "v1", cte_status: "active" },
    { kde_code: "TEMPERATURE", cte_id: "CTE-013", cte_name: "CTE Vận chuyển lạnh — Thủy sản", layer: "Layer 2", owner: "Bộ NN&PTNT", used_version: "v1", cte_status: "active" },
];

export const importPreview: ImportPreviewRow[] = [
    { code: "HARVEST_DATE", name: "Ngày thu hoạch", data_type: "date", change_type: "updated", change_note: "Cập nhật validation_rule" },
    { code: "BATCH_CODE", name: "Mã lô hàng", data_type: "text", change_type: "new" },
    { code: "STORAGE_TEMP", name: "Nhiệt độ bảo quản", data_type: "number", change_type: "new" },
    { code: "LOT_NUMBER", name: "Số lô sản xuất", data_type: "text", change_type: "unchanged" },
];

export const importSummary = {
    new: 12,
    updated: 8,
    unchanged: 104,
};

export function getKdeByCode(code: string): Kde | undefined {
    return kdeLibrary.find((k) => k.code === code);
}

export function getCteUsageByKde(code: string): CteUsage[] {
    return cteUsage.filter((c) => c.kde_code === code);
}
