import type { Mod } from "../types";

/** Truy xuất nguồn gốc › Bằng chứng số (UID) (/truy-xuat/lich-su-quet) */
export const bangChungSoUid: Mod = {
  k: "uid",
  g: "Truy xuất nguồn gốc",
  t: "Bằng chứng số (UID)",
  d: "Mã UID và bằng chứng số gắn với từng UID, mức độ tuân thủ quy trình tiêu chuẩn TXNG",
  href: "/truy-xuat/lich-su-quet",
  cards: [
    {
      id: "H1",
      l: "Tỉ lệ UID đạt đủ công đoạn",
      v: 80650,
      t: 3.2,
      k: "core",
      d: 112950,
      f: "UID có đủ mọi sự kiện bắt buộc của quy trình tiêu chuẩn TXNG được gán / UID đã kích hoạt.",
      goal: 85,
    },
    {
      id: "H2",
      l: "Tỉ lệ UID đã kích hoạt",
      v: 112950,
      t: 0.6,
      k: "core",
      d: 128400,
      f: "UID có sự kiện Kích hoạt mã UID / Tổng UID đã cấp.",
      goal: 90,
    },
    {
      id: "H3",
      l: "Tỉ lệ UID bị thu hồi",
      v: 1240,
      t: 4.1,
      k: "core",
      d: 112950,
      bad: 1,
      f: "UID chuyển trạng thái Đã thu hồi / UID đã kích hoạt.",
    },
    {
      id: "H4",
      l: "UID bất thường trên 10.000 lượt quét",
      v: "1,1",
      t: 23.1,
      k: "core",
      bad: 1,
      f: "UID bị phát hiện bất thường (quét ở nhiều tỉnh trong thời gian ngắn, quét sau thu hồi, lượt quét đột biến) / 10.000 lượt quét.",
    },
    {
      id: "H5",
      l: "Tổng số UID",
      v: 128400,
      t: 18.2,
      k: "scale",
      goalN: 150000,
    },
    { id: "H6", l: "UID cấp mới trong tháng", v: 22400, t: 13.7, k: "scale" },
    {
      id: "H7",
      l: "Tỉ lệ UID đã gán quy trình",
      v: 106950,
      t: 1.8,
      k: "core",
      d: 112950,
      f: "UID đã kích hoạt thuộc sản phẩm đã gán quy trình / UID đã kích hoạt.",
      goal: 90,
    },
    {
      id: "H8",
      l: "Thời gian từ cấp mã đến kích hoạt",
      v: "2,6 ngày",
      t: -8,
      k: "risk",
      bad: 1,
      f: "Trung bình số ngày giữa thời điểm sinh UID và sự kiện kích hoạt.",
    },
  ],
  charts: [
    {
      id: "uid1",
      for: ["H1"],
      t: "Tỉ lệ UID đáp ứng tuân thủ sự kiện trọng yếu",
      f: "UID (hoặc lô) có đủ mọi sự kiện bắt buộc của phiên bản quy trình tiêu chuẩn TXNG được gán / UID đã kích hoạt trong kỳ. UID chưa gán quy trình tính là chưa đạt.",
      type: "ratio",
      items: [
        ["Toàn bộ UID đã kích hoạt", 80650, 112950],
        ["UID cấp đơn vị (SGTIN)", 61200, 84100],
        ["UID cấp lô (LGTIN)", 19450, 28850],
      ],
    },
    {
      id: "uid2",
      for: ["H1"],
      t: "Tỉ lệ UID đạt đủ công đoạn theo quy trình",
      f: "Cùng công thức tuân thủ, nhóm theo quy trình tiêu chuẩn TXNG được gán.",
      type: "hbar",
      pct: 1,
      labels: [
        "Gạo hữu cơ",
        "Sữa tiệt trùng",
        "Rau, quả tươi",
        "Tôm hữu cơ",
        "Cá",
        "Thịt gia súc",
      ],
      ds: [["Đạt đủ công đoạn", [86, 94, 74, 62, 48, 54]]],
    },
    {
      id: "uid3",
      for: ["H1", "H7"],
      t: "Trạng thái tuân thủ của UID",
      f: "Phân loại mỗi UID đã cấp theo trạng thái tại cuối kỳ.",
      type: "doughnut",
      labels: [
        "Đạt đủ công đoạn",
        "Đang thiếu công đoạn",
        "Chưa gán quy trình",
        "Chưa kích hoạt",
        "Bị thu hồi",
      ],
      ds: [["UID", [80650, 26300, 6000, 14210, 1240]]],
    },
    {
      id: "uid4",
      for: ["H2", "H6"],
      t: "UID cấp mới và kích hoạt theo tháng",
      f: "Cấp mới = sinh mã trong tháng. Kích hoạt = có sự kiện kích hoạt (commissioning) trong tháng.",
      type: "line",
      labels: ["T4", "T5", "T6", "T7", "T8", "T9"],
      ds: [
        ["Cấp mới", [12100, 14800, 16900, 18200, 19700, 22400]],
        ["Kích hoạt", [10400, 13100, 15300, 16600, 18100, 20700]],
      ],
    },
    {
      id: "uid5",
      for: ["H2", "H8"],
      t: "Thời gian từ cấp mã đến kích hoạt",
      f: "Số ngày giữa thời điểm sinh UID và sự kiện kích hoạt; chỉ tính UID đã kích hoạt trong kỳ.",
      type: "pie",
      labels: ["≤ 1 ngày", "2–7 ngày", "8–30 ngày", "> 30 ngày"],
      ds: [["UID", [71200, 28400, 9800, 3550]]],
    },
    {
      id: "uid6",
      for: ["H1", "H5"],
      t: "UID theo phân loại GPC",
      f: "Đếm UID đã kích hoạt theo GPC – Segment của sản phẩm; tách đạt đủ công đoạn và chưa đạt.",
      type: "stack",
      labels: [
        "Thực phẩm chế biến",
        "Nông sản tươi",
        "Thủy sản",
        "Sữa & chế phẩm",
        "Bánh kẹo",
        "Dược liệu",
      ],
      ds: [
        ["Đạt đủ công đoạn", [31200, 18400, 9800, 14100, 5300, 1850]],
        ["Chưa đạt", [11900, 8600, 7300, 1100, 2200, 1200]],
      ],
    },
    {
      id: "uid7",
      for: ["H1"],
      t: "Tỉ lệ UID đạt đủ công đoạn theo phân loại GPC",
      f: "UID đạt đủ công đoạn / UID đã kích hoạt của GPC – Segment.",
      type: "hbar",
      pct: 1,
      labels: [
        "Sữa & chế phẩm",
        "Thực phẩm chế biến",
        "Bánh kẹo",
        "Nông sản tươi",
        "Dược liệu",
        "Thủy sản",
      ],
      ds: [["Đạt", [93, 72, 71, 68, 61, 57]]],
    },
    {
      id: "uid8",
      for: ["H3"],
      t: "UID bị thu hồi theo phân loại GPC",
      f: "Cột: UID chuyển trạng thái Thu hồi trong kỳ. Đường: UID thu hồi / UID đã kích hoạt của GPC – Segment.",
      type: "combo",
      y2pct: 1,
      y2free: 1,
      labels: [
        "Thực phẩm chế biến",
        "Nông sản tươi",
        "Thủy sản",
        "Sữa & chế phẩm",
        "Bánh kẹo",
        "Dược liệu",
      ],
      ds: [
        ["UID thu hồi", [420, 380, 290, 60, 70, 20]],
        ["Tỉ lệ thu hồi (%)", [0.9, 1.4, 1.7, 0.4, 0.9, 0.7], "line"],
      ],
    },
    {
      id: "uidR",
      t: "Nguyên nhân UID chưa đạt đủ công đoạn",
      f: "Phân rã UID đã kích hoạt chưa đạt theo nguyên nhân chính; cộng lại bằng số UID chưa đạt (32.300).",
      type: "hbar",
      for: ["H1", "H7"],
      labels: [
        "Thiếu công đoạn bắt buộc",
        "Chưa gán quy trình",
        "Sai thứ tự công đoạn",
        "Khai báo sau thời hạn",
      ],
      ds: [["UID", [21400, 6000, 3100, 1800]]],
    },
    {
      id: "uidM",
      t: "Công đoạn bắt buộc hay bị thiếu",
      f: "Số UID thiếu theo từng công đoạn (một UID có thể thiếu nhiều công đoạn).",
      type: "hbar",
      for: ["H1"],
      labels: [
        "Xuất hàng",
        "Tiếp nhận",
        "Kiểm tra chất lượng",
        "Sản xuất, chế biến",
        "Đóng gói",
      ],
      ds: [["UID", [11400, 9800, 8200, 5600, 2900]]],
    },
    {
      id: "uidL",
      t: "Lý do thu hồi UID",
      f: "Số UID chuyển Đã thu hồi trong kỳ, theo lý do.",
      type: "pie",
      for: ["H3"],
      labels: [
        "Vi phạm ATTP",
        "Ghi nhãn sai",
        "Doanh nghiệp tự thu hồi",
        "Hư hỏng, hết hạn",
      ],
      ds: [["UID", [520, 310, 260, 150]]],
    },
    {
      id: "uidA",
      t: "Bất thường theo loại",
      f: "Số UID bất thường phát hiện trong kỳ, theo dấu hiệu.",
      type: "bar",
      for: ["H4"],
      labels: [
        "Quét nhiều tỉnh",
        "Quét sau thu hồi",
        "Lượt quét đột biến",
        "Mã không tồn tại",
      ],
      ds: [["UID", [28, 14, 12, 10]]],
    },
  ],
  warns: [
    {
      for: ["H3"],
      t: "Lô UID bị thu hồi",
      sev: "critical",
      n: 27,
      cols: ["Mã lô", "Sản phẩm", "Doanh nghiệp", "Lý do", "Ngày"],
      rows: [
        [
          "LGTIN …0425",
          "Rau cải ăn lá",
          "HTX Rau sạch Đông Anh",
          "Dư lượng thuốc BVTV",
          "28/09/2026",
        ],
        [
          "LGTIN …1188",
          "Tôm đông lạnh",
          "Thủy sản Cửu Long",
          "Nhiễm vi sinh",
          "21/09/2026",
        ],
        [
          "LGTIN …0732",
          "Giò chả",
          "Cty TP Hà Thành",
          "Ghi nhãn sai",
          "14/09/2026",
        ],
      ],
    },
    {
      for: ["H2", "H8"],
      t: "UID cấp quá 30 ngày chưa kích hoạt",
      sev: "medium",
      n: 3550,
      cols: ["Sản phẩm", "Doanh nghiệp", "Số UID", "Cấp từ ngày"],
      rows: [
        ["Bánh quy bơ Pháp", "[TEST]", 1200, "12/08/2026"],
        ["Nước mắm Cửu Long", "Thủy sản Cửu Long", 840, "20/08/2026"],
        ["Trà ô long túi lọc", "Cty Chè Tân Cương", 610, "25/08/2026"],
      ],
    },
    {
      for: ["H1"],
      t: "UID thiếu công đoạn bắt buộc",
      sev: "high",
      n: 26300,
      cols: ["Sản phẩm", "Quy trình", "Công đoạn thiếu", "Số UID"],
      rows: [
        [
          "Tôm thẻ đông lạnh",
          "CTE-ORG-SHRIMP v1",
          "Xuất hàng, Tiếp nhận",
          4120,
        ],
        ["Cá basa phi lê", "CTE-FISH v4", "Kiểm tra chất lượng", 3870],
        ["Thịt heo mảnh", "Thịt gia súc v2", "Giết mổ", 2210],
      ],
    },
    {
      for: ["H4"],
      t: "UID có lượt quét bất thường, nghi hàng giả",
      sev: "critical",
      n: 64,
      cols: ["Số sê-ri", "Sản phẩm", "Bất thường", "Lần phát hiện"],
      rows: [
        [
          "i20zhytn34",
          "Bánh quy bơ Pháp",
          "Quét tại 3 tỉnh trong 2 giờ",
          "01/10/2026",
        ],
        [
          "i20j3qwo4g",
          "Bánh quy bơ Pháp",
          "Quét sau khi đã thu hồi",
          "30/09/2026",
        ],
        ["…7741", "Sữa tiệt trùng 180ml", "412 lượt quét/ngày", "29/09/2026"],
      ],
    },
  ],
};
