import type { Mod } from "../types";

/** Quản trị hệ thống › Bộ, ngành, địa phương (/quan-tri/bo-ban-nganh) */
export const boBanNganh: Mod = {
  k: "bo",
  g: "Quản trị hệ thống",
  t: "Bộ, ngành, địa phương",
  d: "Mức độ kết nối của 17 bộ, cơ quan ngang bộ và 34 tỉnh, thành; ban hành quy trình tiêu chuẩn TXNG",
  href: "/quan-tri/bo-ban-nganh",
  cards: [
    {
      id: "H1",
      l: "Bộ, cơ quan ngang bộ đã kết nối",
      v: 9,
      t: 12.5,
      k: "core",
      d: 17,
      f: "Mẫu số cố định: 14 bộ và 3 cơ quan ngang bộ.",
      goal: 80,
    },
    {
      id: "H2",
      l: "Tỉnh/thành đã kết nối",
      v: 21,
      t: 10.5,
      k: "core",
      d: 34,
      f: "Mẫu số cố định: 34 tỉnh, thành sau sắp xếp.",
      goal: 80,
    },
    {
      id: "H3",
      l: "Tỉ lệ nhóm hàng bắt buộc có quy trình",
      v: 14,
      t: 7.7,
      k: "core",
      d: 22,
      f: "Nhóm hàng thuộc diện bắt buộc truy xuất đã có ≥ 1 quy trình tiêu chuẩn TXNG đang áp dụng / Tổng nhóm hàng bắt buộc.",
      goal: 85,
    },
    {
      id: "H4",
      l: "Tỉ lệ UID đạt theo quy trình do bộ ban hành",
      v: 78300,
      t: 2.6,
      k: "core",
      d: 106950,
      f: "UID đạt đủ công đoạn / UID đã kích hoạt được gán quy trình do các bộ ban hành. Đo hiệu quả thực thi tiêu chuẩn.",
      goal: 85,
    },
    {
      id: "H5",
      l: "Quy trình tiêu chuẩn TXNG đã ban hành",
      v: 64,
      t: 6.7,
      k: "scale",
      goalN: 80,
    },
    { id: "H6", l: "Tỉnh/thành có Sở đầu mối", v: 18, t: 12.5, k: "scale" },
    {
      id: "H7",
      l: "Bộ, cơ quan ngang bộ chưa kết nối",
      v: 8,
      t: -11.1,
      k: "risk",
      bad: 1,
    },
    {
      id: "H8",
      l: "Tỉnh/thành chưa kết nối",
      v: 13,
      t: -13.3,
      k: "risk",
      bad: 1,
    },
  ],
  charts: [
    {
      id: "bo1",
      for: ["H1"],
      t: "Mức độ tham gia của bộ, cơ quan ngang bộ",
      f: "Số cơ quan đạt tiêu chí / 17 (14 bộ và 3 cơ quan ngang bộ).",
      type: "ratio",
      items: [
        ["Đã kết nối nền tảng", 9, 17],
        ["Đã ban hành ≥ 1 quy trình tiêu chuẩn TXNG", 5, 17],
        ["Có quy trình đang được doanh nghiệp áp dụng", 4, 17],
        ["Đã phủ quy trình cho mọi nhóm hàng bắt buộc thuộc phạm vi", 1, 17],
      ],
    },
    {
      id: "bo2",
      for: ["H1", "H7"],
      t: "Cơ cấu 17 cơ quan theo mức độ tham gia",
      f: "Phân loại mỗi cơ quan theo mức cao nhất đạt được; tổng bằng 17.",
      type: "pie",
      labels: [
        "Đã kết nối, đã ban hành quy trình",
        "Đã kết nối, chưa ban hành quy trình",
        "Chưa kết nối",
      ],
      ds: [["Cơ quan", [5, 4, 8]]],
    },
    {
      id: "bo3",
      for: ["H5"],
      t: "Quy trình tiêu chuẩn TXNG theo bộ",
      f: "Đếm quy trình theo cơ quan ban hành; tách Đang áp dụng và Dự thảo.",
      type: "stack",
      labels: ["NN&MT", "Y tế", "Công Thương", "KH&CN", "Tài chính"],
      ds: [
        ["Đang áp dụng", [26, 14, 12, 8, 4]],
        ["Dự thảo", [5, 3, 6, 1, 2]],
      ],
    },
    {
      id: "bo4",
      for: ["H3"],
      t: "Nhóm hàng thuộc phạm vi quản lý đã có quy trình",
      f: "GPC – Family thuộc phạm vi bộ đã có ≥ 1 quy trình tiêu chuẩn TXNG đang áp dụng / Tổng GPC – Family thuộc phạm vi bộ.",
      type: "hbar",
      pct: 1,
      labels: ["NN&MT", "Y tế", "Công Thương"],
      ds: [["Đã có quy trình", [81, 62, 43]]],
    },
    {
      id: "bo5",
      for: ["H4"],
      t: "UID áp dụng và tỉ lệ đạt theo bộ ban hành quy trình",
      f: "Cột: UID đã kích hoạt được gán quy trình do bộ ban hành. Đường: UID đạt đủ công đoạn / UID đó. Đo hiệu quả thực thi tiêu chuẩn của từng bộ.",
      type: "combo",
      y2pct: 1,
      labels: ["Bộ Y tế", "Bộ NN&MT", "Bộ KH&CN", "Bộ Công Thương"],
      ds: [
        ["UID áp dụng", [31400, 48200, 9300, 18050]],
        ["Tỉ lệ đạt (%)", [82, 73, 69, 58], "line"],
      ],
    },
    {
      id: "bo6",
      for: ["H5"],
      t: "Quy trình tiêu chuẩn TXNG ban hành lũy kế",
      f: "Đếm lũy kế quy trình chuyển sang trạng thái Đang áp dụng, theo cơ quan ban hành.",
      type: "line",
      labels: ["T4", "T5", "T6", "T7", "T8", "T9"],
      ds: [
        ["Bộ NN&MT", [14, 17, 19, 22, 24, 26]],
        ["Bộ Y tế", [6, 8, 9, 11, 13, 14]],
        ["Bộ Công Thương", [4, 5, 7, 9, 10, 12]],
      ],
    },
    {
      id: "bo8",
      for: ["H2", "H6"],
      t: "Mức độ tham gia của 34 tỉnh/thành",
      f: "Số tỉnh/thành đạt tiêu chí / 34.",
      type: "ratio",
      items: [
        ["Đã kết nối nền tảng", 21, 34],
        ["Có Sở đầu mối đã cấu hình phạm vi", 18, 34],
        ["Có doanh nghiệp khai báo sự kiện", 26, 34],
        ["Đạt chỉ số tuân thủ ≥ 80%", 6, 34],
      ],
    },
    {
      id: "bo9",
      for: ["H2", "H8"],
      t: "Kết nối theo vùng",
      f: "Đếm tỉnh/thành đã và chưa kết nối theo vùng kinh tế.",
      type: "stack",
      labels: [
        "Đồng bằng sông Hồng",
        "Trung du, miền núi phía Bắc",
        "Bắc Trung Bộ, duyên hải",
        "Tây Nguyên",
        "Đông Nam Bộ",
        "Đồng bằng sông Cửu Long",
      ],
      ds: [
        ["Đã kết nối", [5, 3, 5, 1, 3, 4]],
        ["Chưa kết nối", [1, 4, 2, 1, 1, 4]],
      ],
    },
    {
      id: "bo10",
      for: ["H2"],
      t: "Tỉnh/thành kết nối mới và lũy kế",
      f: "Cột: tỉnh/thành kết nối trong tháng. Đường: tổng lũy kế.",
      type: "combo",
      labels: ["T4", "T5", "T6", "T7", "T8", "T9"],
      ds: [
        ["Kết nối mới", [3, 3, 2, 3, 3, 2]],
        ["Lũy kế", [8, 11, 13, 16, 19, 21], "line"],
      ],
    },
    {
      id: "bo7",
      for: ["H4"],
      t: "Tỉ lệ UID đạt đủ công đoạn theo tỉnh/thành",
      f: "UID đạt đủ công đoạn / UID đã kích hoạt của doanh nghiệp có trụ sở tại tỉnh; 6 tỉnh nhiều UID nhất.",
      type: "hbar",
      pct: 1,
      labels: [
        "Hà Nội",
        "TP.HCM",
        "Lâm Đồng",
        "Đà Nẵng",
        "Hải Phòng",
        "Long An",
      ],
      ds: [["UID đạt", [78, 74, 72, 71, 69, 63]]],
    },
    {
      id: "boM",
      t: "Nhóm hàng bắt buộc chưa có quy trình theo bộ",
      f: "Số nhóm hàng thuộc diện bắt buộc trong phạm vi bộ chưa có quy trình tiêu chuẩn TXNG đang áp dụng.",
      type: "bar",
      for: ["H3"],
      labels: ["Bộ Công Thương", "Bộ Y tế", "Bộ NN&MT"],
      ds: [["Nhóm hàng", [4, 3, 1]]],
    },
  ],
  warns: [
    {
      for: ["H1", "H7"],
      t: "Bộ, cơ quan ngang bộ chưa kết nối",
      sev: "high",
      n: 8,
      cols: ["Cơ quan", "Loại", "Ngày gửi đề nghị", "Trạng thái"],
      rows: [
        ["Bộ Xây dựng", "Bộ", "15/07/2026", "Chưa phản hồi"],
        [
          "Bộ Văn hóa, Thể thao và Du lịch",
          "Bộ",
          "15/07/2026",
          "Đang chuẩn bị đầu mối",
        ],
        [
          "Ngân hàng Nhà nước Việt Nam",
          "Cơ quan ngang bộ",
          "01/08/2026",
          "Chưa phản hồi",
        ],
        [
          "Thanh tra Chính phủ",
          "Cơ quan ngang bộ",
          "01/08/2026",
          "Không thuộc phạm vi",
        ],
      ],
    },
    {
      for: ["H3", "H5"],
      t: "Đã kết nối nhưng chưa ban hành quy trình tiêu chuẩn TXNG",
      sev: "medium",
      n: 4,
      cols: ["Cơ quan", "Ngày kết nối", "Quy trình đang dự thảo"],
      rows: [
        ["Bộ Tài chính", "20/05/2026", 2],
        ["Bộ Công an", "02/08/2026", 0],
        ["Bộ Quốc phòng", "15/08/2026", 0],
      ],
    },
    {
      for: ["H3"],
      t: "Nhóm hàng bắt buộc chưa có quy trình tiêu chuẩn TXNG",
      sev: "critical",
      n: 8,
      cols: ["Phân loại GPC", "Bộ quản lý", "Sản phẩm bị ảnh hưởng"],
      rows: [
        ["Thực phẩm chức năng", "Bộ Y tế", 642],
        ["Rượu, bia", "Bộ Công Thương", 318],
        ["Nước giải khát", "Bộ Công Thương", 276],
        ["Muối", "Bộ NN&MT", 94],
      ],
    },
    {
      for: ["H4", "H5"],
      t: "Quy trình tiêu chuẩn TXNG quá 12 tháng chưa rà soát",
      sev: "medium",
      n: 5,
      cols: ["Quy trình", "Cơ quan", "Cập nhật cuối", "Sản phẩm đang áp dụng"],
      rows: [
        ["Thịt gia súc v2", "Bộ NN&MT", "12/08/2025", 412],
        ["Thủy sản xuất khẩu v1", "Bộ NN&MT", "30/09/2025", 188],
      ],
    },
    {
      for: ["H2", "H8"],
      t: "Tỉnh/thành chưa kết nối",
      sev: "high",
      n: 13,
      cols: ["Tỉnh/thành", "Vùng", "Doanh nghiệp trên nền tảng", "Tình trạng"],
      rows: [
        ["Sơn La", "Trung du, miền núi phía Bắc", 31, "Đã có đầu mối"],
        ["Cà Mau", "Đồng bằng sông Cửu Long", 12, "Chưa phản hồi"],
        ["Lai Châu", "Trung du, miền núi phía Bắc", 3, "Chưa phản hồi"],
        ["Gia Lai", "Tây Nguyên", 18, "Đang thẩm định"],
      ],
    },
    {
      for: ["H4"],
      t: "Tỉnh/thành có tỉ lệ UID đạt giảm quá 5 điểm so tháng trước",
      sev: "critical",
      n: 3,
      cols: [
        "Tỉnh/thành",
        "Tháng trước",
        "Tháng này",
        "Công đoạn thiếu nhiều nhất",
      ],
      rows: [
        ["Long An", "70%", "63%", "Xuất hàng"],
        ["Cần Thơ", "64%", "58%", "Kiểm tra chất lượng"],
        ["Nghệ An", "61%", "55%", "Tiếp nhận"],
      ],
    },
  ],
};
