import type { Mod } from "../types";

/** Truy xuất nguồn gốc › Chứng chỉ số sự kiện (/truy-xuat/su-kien) */
export const chungChiSoSuKien: Mod = {
  k: "sk",
  g: "Truy xuất nguồn gốc",
  t: "Chứng chỉ số sự kiện",
  d: "Chứng chỉ số được khởi tạo tại các sự kiện trọng yếu: khối lượng, chất lượng và độ kịp thời",
  href: "/truy-xuat/su-kien",
  cards: [
    {
      id: "H1",
      l: "Tỉ lệ chứng chỉ số hợp lệ",
      v: 480950,
      t: 0.4,
      k: "core",
      d: 486200,
      f: "Chứng chỉ số xác minh chữ ký và dữ liệu hợp lệ / Tổng chứng chỉ số.",
      goal: 90,
    },
    {
      id: "H2",
      l: "Tỉ lệ khai báo trong 24 giờ",
      v: 453140,
      t: 1.1,
      k: "core",
      d: 486200,
      f: "Thời điểm phát hành − thời điểm xảy ra ≤ 24 giờ / Tổng chứng chỉ số.",
      goal: 90,
    },
    {
      id: "H3",
      l: "Tỉ lệ đủ KDE bắt buộc",
      v: 469300,
      t: 0.8,
      k: "core",
      d: 486200,
      f: "Đủ dữ liệu quan trọng (KDE) bắt buộc của sự kiện trọng yếu / Tổng chứng chỉ số.",
      goal: 90,
    },
    {
      id: "H4",
      l: "Tỉ lệ đã neo NDAChain",
      v: 472600,
      t: 0.2,
      k: "core",
      d: 486200,
      f: "Chứng chỉ số đã có bằng chứng neo trên NDAChain / Tổng chứng chỉ số.",
      goal: 90,
    },
    {
      id: "H5",
      l: "Tổng số chứng chỉ số sự kiện",
      v: 486200,
      t: 22.5,
      k: "scale",
      goalN: 550000,
    },
    { id: "H6", l: "Phát hành trong tháng", v: 97980, t: 10, k: "scale" },
    {
      id: "H7",
      l: "Doanh nghiệp phát hành trong tháng",
      v: 264,
      t: 5.2,
      k: "scale",
    },
    {
      id: "H8",
      l: "Thời gian khai báo trung bình",
      v: "6,8 giờ",
      t: -17.1,
      k: "risk",
      bad: 1,
      f: "Trung bình khoảng cách giữa thời điểm xảy ra và thời điểm phát hành.",
    },
  ],
  charts: [
    {
      id: "sk1",
      for: ["H1", "H2", "H3", "H4"],
      t: "Tỉ lệ đáp ứng tiêu chuẩn chất lượng khai báo",
      f: "Chứng chỉ số đạt tiêu chí / Tổng chứng chỉ số phát hành trong kỳ (486.200).",
      type: "ratio",
      items: [
        ["Chữ ký số hợp lệ", 483900, 486200],
        ["Đã neo NDAChain", 472600, 486200],
        ["Đủ KDE bắt buộc theo quy trình", 469300, 486200],
        ["Khai báo trong 24 giờ", 453140, 486200],
      ],
    },
    {
      id: "sk2",
      for: ["H1", "H5"],
      t: "Chứng chỉ số hợp lệ và tỉ lệ bị từ chối theo tháng",
      f: "Cột: chứng chỉ số hợp lệ theo thời điểm phát hành. Đường: Chứng chỉ số bị từ chối / Tổng chứng chỉ số phát hành trong tháng.",
      type: "combo",
      y2pct: 1,
      y2free: 1,
      labels: ["T4", "T5", "T6", "T7", "T8", "T9"],
      ds: [
        ["Chứng chỉ số hợp lệ", [52100, 61800, 70400, 79200, 88300, 97100]],
        ["Tỉ lệ từ chối (%)", [2.7, 2.1, 1.6, 1.3, 1, 0.9], "line"],
      ],
    },
    {
      id: "sk3",
      for: ["H6"],
      t: "Cơ cấu chứng chỉ số theo công đoạn nghiệp vụ",
      f: "Đếm chứng chỉ số hợp lệ theo công đoạn nghiệp vụ (bizStep).",
      type: "pie",
      labels: [
        "Kích hoạt mã UID",
        "Sản xuất, chế biến",
        "Đóng gói",
        "Xuất hàng",
        "Tiếp nhận",
      ],
      ds: [["Chứng chỉ số", [168400, 121900, 74300, 63800, 52550]]],
    },
    {
      id: "sk4",
      for: ["H2", "H8"],
      t: "Độ kịp thời khai báo",
      f: "Khoảng cách giữa thời điểm xảy ra (eventTime) và thời điểm phát hành (recordTime).",
      type: "bar",
      labels: ["≤ 24 giờ", "1–3 ngày", "3–7 ngày", "> 7 ngày"],
      ds: [["Chứng chỉ số", [453140, 18200, 9100, 5760]]],
    },
    {
      id: "sk5",
      for: ["H1"],
      t: "Lý do chứng chỉ số bị từ chối",
      f: "Đếm chứng chỉ số bị từ chối theo lý do đầu tiên được ghi nhận.",
      type: "hbar",
      labels: [
        "Thiếu KDE bắt buộc",
        "Sai chữ ký số",
        "UID không tồn tại",
        "Sai thứ tự công đoạn",
        "Cơ sở không khớp GLN",
      ],
      ds: [["Chứng chỉ số", [2140, 1180, 860, 640, 430]]],
    },
    {
      id: "sk6",
      for: ["H2"],
      t: "Tỉ lệ khai báo trong 24 giờ theo tháng",
      f: "Chứng chỉ số phát hành trong vòng 24 giờ kể từ thời điểm xảy ra / Tổng chứng chỉ số trong tháng.",
      type: "line",
      pct: 1,
      labels: ["T4", "T5", "T6", "T7", "T8", "T9"],
      ds: [["Trong 24 giờ", [84, 86, 88, 90, 92, 93]]],
    },
    {
      id: "skU",
      t: "Tỉ lệ bị từ chối theo đơn vị cung cấp giải pháp",
      f: "Chứng chỉ số bị từ chối / Chứng chỉ số gửi qua đơn vị.",
      type: "hbar",
      for: ["H1"],
      pct: 1,
      y_free: 1,
      labels: ["Test Đại Lý 01", "P6_Thanh", "ThanhTP", "TrangNTT", "Checkee"],
      ds: [["Từ chối", [8.5, 6.5, 5.5, 1.8, 0.6]]],
    },
    {
      id: "skD",
      t: "Thời gian khai báo trung bình theo công đoạn",
      f: "Trung bình (giờ) giữa thời điểm xảy ra và thời điểm phát hành, theo công đoạn.",
      type: "hbar",
      for: ["H2", "H8"],
      labels: [
        "Tiếp nhận",
        "Xuất hàng",
        "Kiểm tra chất lượng",
        "Sản xuất, chế biến",
        "Kích hoạt mã UID",
      ],
      ds: [["Giờ", [14.2, 11.6, 9.8, 4.1, 1.2]]],
    },
    {
      id: "skK",
      t: "KDE bắt buộc hay thiếu",
      f: "Số chứng chỉ số thiếu từng KDE bắt buộc.",
      type: "hbar",
      for: ["H3"],
      labels: [
        "Nhiệt độ bảo quản",
        "Địa điểm nhận (GLN)",
        "Số lô",
        "Ngày sản xuất",
        "Người thực hiện",
      ],
      ds: [["Chứng chỉ số", [6800, 4100, 2900, 1700, 1400]]],
    },
    {
      id: "skN",
      t: "Thời gian chờ neo NDAChain",
      f: "Số chứng chỉ số theo thời gian từ phát hành đến khi có bằng chứng neo.",
      type: "bar",
      for: ["H4"],
      labels: ["≤ 1 phút", "1–10 phút", "10–60 phút", "> 1 giờ", "Chưa neo"],
      ds: [["Chứng chỉ số", [402100, 61400, 9100, 0, 13600]]],
    },
    {
      id: "skE",
      t: "Doanh nghiệp phát hành theo đơn vị cung cấp giải pháp",
      f: "Doanh nghiệp có ≥ 1 chứng chỉ số trong tháng, theo đơn vị ủy quyền.",
      type: "bar",
      for: ["H7"],
      labels: ["TrangNTT", "ThanhTP", "Checkee", "Test Đại Lý 01", "Khác"],
      ds: [["Doanh nghiệp", [94, 58, 41, 31, 40]]],
    },
  ],
  warns: [
    {
      for: ["H1"],
      t: "Chứng chỉ số bị từ chối trong 7 ngày",
      sev: "high",
      n: 1240,
      cols: ["Thời gian", "Doanh nghiệp", "Sự kiện trọng yếu", "Lý do"],
      rows: [
        ["01/10 14:22", "Thủy sản Cửu Long", "Xuất hàng", "Thiếu KDE nhiệt độ"],
        [
          "01/10 09:05",
          "Cty TP Hà Thành",
          "Sản xuất, chế biến",
          "Sai chữ ký số",
        ],
        ["30/09 16:41", "[TEST]", "Kích hoạt mã UID", "UID không tồn tại"],
        ["30/09 11:18", "HTX Phước An", "Tiếp nhận", "Sai thứ tự công đoạn"],
      ],
    },
    {
      for: ["H2", "H8"],
      t: "Chứng chỉ số khai báo bù quá 7 ngày",
      sev: "medium",
      n: 5760,
      cols: [
        "Doanh nghiệp",
        "Sự kiện trọng yếu",
        "Thời điểm xảy ra",
        "Thời điểm phát hành",
      ],
      rows: [
        ["Cty CP Tech Brand", "Xuất hàng", "02/09/2026", "28/09/2026"],
        ["HTX Chè Mộc Châu", "Thu hoạch", "05/09/2026", "24/09/2026"],
        ["Lafooco", "Đóng gói", "10/09/2026", "22/09/2026"],
      ],
    },
    {
      for: ["H4"],
      t: "Chứng chỉ số chưa neo NDAChain quá 1 giờ",
      sev: "high",
      n: 318,
      cols: [
        "Mã chứng chỉ số",
        "Doanh nghiệp",
        "Thời điểm phát hành",
        "Trạng thái neo",
      ],
      rows: [
        ["evt-9f21…", "Masan", "01/10 10:12", "Đang chờ"],
        ["evt-71ac…", "Lafooco", "01/10 08:47", "Lỗi kết nối nút"],
        ["evt-03bd…", "HTX Phước An", "30/09 22:30", "Đang chờ"],
      ],
    },
  ],
};
