import type { Mod } from "../types";

/** Truy xuất nguồn gốc › Cơ sở, địa điểm (/truy-xuat/co-so) */
export const coSo: Mod = {
  k: "cs",
  g: "Truy xuất nguồn gốc",
  t: "Cơ sở, địa điểm",
  d: "Cơ sở, địa điểm sản xuất, kinh doanh định danh bằng mã GLN",
  href: "/truy-xuat/co-so",
  cards: [
    {
      id: "H1",
      l: "Tỉ lệ cơ sở diện bắt buộc có chứng nhận ATTP",
      v: 531,
      t: 2.4,
      k: "core",
      d: 720,
      f: "Cơ sở thuộc diện bắt buộc có giấy chứng nhận đủ điều kiện ATTP còn hiệu lực / Cơ sở thuộc diện bắt buộc.",
      goal: 90,
    },
    {
      id: "H2",
      l: "Tỉ lệ cơ sở có GLN",
      v: 902,
      t: 1.1,
      k: "core",
      d: 1064,
      f: "Cơ sở, địa điểm đã có mã GLN / Tổng số cơ sở, địa điểm.",
      goal: 90,
    },
    {
      id: "H3",
      l: "Tỉ lệ cơ sở có mã hành chính chuẩn",
      v: 968,
      t: 0.9,
      k: "core",
      d: 1064,
      f: "Có đủ mã tỉnh và mã xã theo danh mục hiện hành / Tổng số cơ sở.",
      goal: 90,
    },
    {
      id: "H4",
      l: "Tỉ lệ cơ sở hoạt động",
      v: 755,
      t: 3,
      k: "core",
      d: 1064,
      f: "Là nơi xảy ra ≥ 1 sự kiện trong 30 ngày / Tổng số cơ sở.",
      goal: 80,
    },
    {
      id: "H5",
      l: "Tổng số cơ sở, địa điểm",
      v: 1064,
      t: 3.8,
      k: "scale",
      goalN: 1200,
    },
    { id: "H6", l: "Cơ sở mới trong tháng", v: 84, t: 9.1, k: "scale" },
    {
      id: "H7",
      l: "Chứng nhận ATTP sắp hết hiệu lực",
      v: 23,
      t: 27.8,
      k: "risk",
      bad: 1,
    },
    { id: "H8", l: "Cơ sở ngừng hoạt động", v: 38, t: 11.8, k: "risk", bad: 1 },
  ],
  charts: [
    {
      id: "cs1",
      for: ["H2", "H3"],
      t: "Độ đầy đủ hồ sơ cơ sở",
      f: "Số cơ sở có trường hợp lệ / Tổng số cơ sở (1.064).",
      type: "ratio",
      items: [
        ["Có GLN (mã địa điểm GS1)", 902, 1064],
        ["Có mã đơn vị hành chính chuẩn", 968, 1064],
        ["Có nhóm sản phẩm", 877, 1064],
        ["Có tọa độ GPS", 811, 1064],
      ],
    },
    {
      id: "cs2",
      for: ["H1"],
      t: "Cơ sở thuộc diện bắt buộc có chứng nhận ATTP",
      f: "Cơ sở thuộc diện phải có giấy chứng nhận đủ điều kiện ATTP và đang có chứng nhận còn hiệu lực / Cơ sở thuộc diện bắt buộc, theo loại hình.",
      type: "hbar",
      pct: 1,
      labels: [
        "Sản xuất thực phẩm",
        "Sơ chế, đóng gói",
        "Nhà hàng, ăn uống",
        "Kinh doanh, bán lẻ",
        "Kho, trung chuyển",
      ],
      ds: [["Tỉ lệ có chứng nhận", [82, 76, 61, 58, 44]]],
    },
    {
      id: "cs3",
      for: ["H5"],
      t: "Cơ cấu cơ sở theo loại hình",
      f: "Đếm theo loại hình cơ sở chính; cơ sở nhiều loại hình đếm theo loại đầu tiên.",
      type: "pie",
      labels: [
        "Sản xuất thực phẩm",
        "Kinh doanh, bán lẻ",
        "Nhà hàng, ăn uống",
        "Kho, trung chuyển",
        "Chưa phân loại",
      ],
      ds: [["Cơ sở", [412, 298, 121, 84, 149]]],
    },
    {
      id: "cs4",
      for: ["H1", "H5"],
      t: "Cơ sở theo tỉnh/thành",
      f: "Đếm cơ sở theo mã tỉnh của địa chỉ; tách có và chưa có giấy tờ, chứng nhận còn hiệu lực.",
      type: "stack",
      labels: ["Hà Nội", "TP.HCM", "Long An", "Lâm Đồng", "Cần Thơ", "Đà Nẵng"],
      ds: [
        ["Có giấy tờ, chứng nhận", [221, 148, 51, 40, 33, 29]],
        ["Chưa có", [165, 93, 41, 31, 27, 22]],
      ],
    },
    {
      id: "cs5",
      for: ["H4"],
      t: "Cơ sở phát sinh sự kiện theo tháng",
      f: "Cột: số cơ sở là nơi xảy ra ≥ 1 sự kiện trong tháng. Đường: số cơ sở đó / Tổng cơ sở đang hoạt động.",
      type: "combo",
      y2pct: 1,
      labels: ["T4", "T5", "T6", "T7", "T8", "T9"],
      ds: [
        ["Cơ sở hoạt động", [594, 627, 651, 683, 709, 755]],
        ["Tỉ lệ hoạt động (%)", [58, 61, 63, 66, 68, 71], "line"],
      ],
    },
    {
      id: "cs6",
      for: ["H2", "H6"],
      t: "Cơ sở định danh GLN mới theo tháng",
      f: "Số cơ sở được cấp GLN trong tháng, tách cơ sở sản xuất và cơ sở kinh doanh.",
      type: "line",
      labels: ["T4", "T5", "T6", "T7", "T8", "T9"],
      ds: [
        ["Cơ sở sản xuất", [28, 31, 36, 34, 41, 45]],
        ["Cơ sở kinh doanh", [22, 27, 30, 33, 35, 39]],
      ],
    },
    {
      id: "csT",
      t: "Tỉ lệ cơ sở có mã hành chính chuẩn theo tỉnh/thành",
      f: "Cơ sở có đủ mã tỉnh, xã chuẩn / Cơ sở của tỉnh.",
      type: "hbar",
      for: ["H3"],
      pct: 1,
      labels: ["Hà Nội", "Lâm Đồng", "Đà Nẵng", "Cần Thơ", "Long An", "TP.HCM"],
      ds: [["Có mã chuẩn", [95, 90, 92, 78, 75, 74]]],
    },
    {
      id: "csA",
      t: "Tỉ lệ cơ sở hoạt động theo loại hình",
      f: "Cơ sở là nơi xảy ra sự kiện trong 30 ngày / Cơ sở của loại hình.",
      type: "hbar",
      for: ["H4"],
      pct: 1,
      labels: [
        "Sản xuất thực phẩm",
        "Kho, trung chuyển",
        "Kinh doanh, bán lẻ",
        "Nhà hàng, ăn uống",
      ],
      ds: [["Hoạt động", [84, 77, 63, 41]]],
    },
    {
      id: "csE",
      t: "Chứng nhận ATTP sắp hết hiệu lực 3 tháng tới",
      f: "Cơ sở diện bắt buộc có chứng nhận ATTP hết hiệu lực trong từng tháng tới.",
      type: "bar",
      for: ["H1", "H7"],
      labels: ["T10", "T11", "T12"],
      ds: [["Cơ sở", [23, 31, 18]]],
    },
    {
      id: "csS",
      t: "Cơ sở mới và ngừng hoạt động theo tháng",
      f: "Mới: cơ sở tạo trong tháng. Ngừng: chuyển trạng thái Ngừng hoạt động trong tháng.",
      type: "line",
      for: ["H6", "H8"],
      labels: ["T4", "T5", "T6", "T7", "T8", "T9"],
      ds: [
        ["Cơ sở mới", [52, 61, 66, 70, 77, 84]],
        ["Ngừng hoạt động", [4, 6, 5, 7, 5, 8]],
      ],
    },
  ],
  warns: [
    {
      for: ["H3"],
      t: "Cơ sở thiếu mã đơn vị hành chính chuẩn",
      sev: "high",
      n: 96,
      cols: ["Cơ sở", "Doanh nghiệp", "Địa chỉ đang khai", "Lý do"],
      rows: [
        [
          "Cơ sở sản xuất",
          "Doanh nghiệp",
          "Số 8 Ngô Thì Nhậm",
          "Không có tỉnh, xã",
        ],
        ["Quầy bán lẻ Thái Hà", "[TEST]", "Số 8 Thái Hà", "Không có tỉnh, xã"],
        [
          "Cty TNHH Tech Brand",
          "Tech Brand",
          "Số 138 phố Nguyễn Lân",
          "Không có tỉnh, xã",
        ],
        [
          "Kho Bình Chánh",
          "Masan",
          "Xã Bình Chánh, TP.HCM",
          "Mã xã cũ trước sắp xếp",
        ],
      ],
    },
    {
      for: ["H1"],
      t: "Cơ sở diện bắt buộc chưa có chứng nhận ATTP",
      sev: "critical",
      n: 187,
      cols: ["Cơ sở", "Loại hình", "Tỉnh/thành", "Sản phẩm đang bán"],
      rows: [
        ["Nhà hàng Trung Hoa", "Nhà hàng, ăn uống", "Hà Nội", 12],
        ["Cơ sở giết mổ Đông Anh", "Sản xuất thực phẩm", "Hà Nội", 6],
        ["Kho lạnh Cái Răng", "Kho, trung chuyển", "Cần Thơ", 31],
        ["Bếp ăn KCN Đức Hòa", "Nhà hàng, ăn uống", "Long An", 4],
      ],
    },
    {
      for: ["H4", "H8"],
      t: "Cơ sở không phát sinh sự kiện quá 90 ngày",
      sev: "medium",
      n: 142,
      cols: ["Cơ sở", "Doanh nghiệp", "Sự kiện cuối", "Trạng thái"],
      rows: [
        ["Cơ sở Hà Nội", "Doanh nghiệp", "09/06/2026", "Hoạt động"],
        ["Cty TNHH MTV DV 5 Cua", "5 Cua", "24/03/2026", "Hoạt động"],
        [
          "Vùng trồng Mộc Châu 02",
          "HTX Chè Mộc Châu",
          "15/05/2026",
          "Hoạt động",
        ],
      ],
    },
  ],
};
