import type { Mod } from "../types";

/** Truy xuất nguồn gốc › Doanh nghiệp (/quan-tri/doanh-nghiep) */
export const doanhNghiep: Mod = {
  k: "dn",
  g: "Truy xuất nguồn gốc",
  t: "Doanh nghiệp",
  d: "Mức độ tuân thủ truy xuất nguồn gốc của doanh nghiệp",
  href: "/quan-tri/doanh-nghiep",
  cards: [
    {
      id: "H1",
      l: "Tỉ lệ doanh nghiệp có sản phẩm",
      v: 375,
      t: 2.1,
      k: "core",
      d: 436,
      f: "Doanh nghiệp đã khai báo ≥ 1 sản phẩm (mã GTIN) / Tổng số doanh nghiệp.",
      goal: 90,
    },
    {
      id: "H2",
      l: "Tỉ lệ doanh nghiệp hoạt động",
      v: 264,
      t: 3.4,
      k: "core",
      d: 436,
      f: "Doanh nghiệp có ≥ 1 chứng chỉ số sự kiện trong 30 ngày / Tổng số doanh nghiệp.",
      goal: 80,
    },
    {
      id: "H3",
      l: "Tỉ lệ doanh nghiệp có UID đạt đủ công đoạn",
      v: 290,
      t: 4,
      k: "core",
      d: 436,
      f: "Doanh nghiệp có ≥ 1 UID đạt đủ công đoạn theo quy trình tiêu chuẩn TXNG / Tổng số doanh nghiệp.",
      goal: 80,
    },
    {
      id: "H4",
      l: "Tỉ lệ doanh nghiệp có 100% sản phẩm đủ dữ liệu chủ",
      v: 112,
      t: 5.2,
      k: "core",
      d: 375,
      f: "Doanh nghiệp có mọi sản phẩm đủ dữ liệu chủ / Doanh nghiệp có sản phẩm.",
      goal: 80,
    },
    {
      id: "H5",
      l: "Tổng số doanh nghiệp",
      v: 436,
      t: 6.2,
      k: "scale",
      goalN: 500,
    },
    { id: "H6", l: "Doanh nghiệp mới trong tháng", v: 68, t: 11.5, k: "scale" },
    {
      id: "H7",
      l: "Không phát sinh sự kiện quá 90 ngày",
      v: 39,
      t: -4.9,
      k: "risk",
      bad: 1,
    },
    {
      id: "H8",
      l: "Tỉ lệ giữ chân doanh nghiệp hoạt động",
      v: 236,
      t: 1.2,
      k: "core",
      d: 251,
      f: "Doanh nghiệp hoạt động tháng trước vẫn hoạt động tháng này / Doanh nghiệp hoạt động tháng trước.",
      goal: 90,
    },
  ],
  charts: [
    {
      id: "dn1",
      for: ["H1", "H3"],
      t: "Mức độ tham gia của doanh nghiệp",
      f: "Số doanh nghiệp đạt từng bước / Tổng số doanh nghiệp (436). Mỗi bước đếm độc lập.",
      type: "ratio",
      items: [
        ["Có ≥ 1 sản phẩm đã khai báo", 375, 436],
        ["Có sản phẩm đã gán quy trình tiêu chuẩn TXNG", 298, 436],
        ["Phát sinh chứng chỉ số sự kiện trong 30 ngày", 264, 436],
        ["Có ≥ 1 UID đạt đủ công đoạn", 290, 436],
      ],
    },
    {
      id: "dn2",
      for: ["H3"],
      t: "Tỉ lệ UID đạt đủ công đoạn theo phân loại GPC",
      f: "UID đạt đủ công đoạn / UID đã kích hoạt của các doanh nghiệp, nhóm theo GPC – Segment chính của doanh nghiệp.",
      type: "hbar",
      pct: 1,
      labels: [
        "Sữa & chế phẩm",
        "Thủy sản",
        "Thực phẩm chế biến",
        "Nông sản tươi",
        "Dược liệu",
      ],
      ds: [["UID đạt", [93, 57, 72, 68, 61]]],
    },
    {
      id: "dn3",
      for: ["H1", "H2", "H5"],
      t: "Doanh nghiệp có sản phẩm và doanh nghiệp hoạt động theo tháng",
      f: "Có sản phẩm: lũy kế doanh nghiệp đã khai báo ≥ 1 sản phẩm. Hoạt động: có chứng chỉ số sự kiện trong 30 ngày tính đến cuối tháng.",
      type: "line",
      labels: ["T4", "T5", "T6", "T7", "T8", "T9"],
      ds: [
        ["Có sản phẩm", [269, 291, 318, 338, 361, 375]],
        ["Hoạt động", [182, 201, 224, 238, 251, 264]],
      ],
    },
    {
      id: "dn4",
      for: ["H4"],
      t: "Phân bố doanh nghiệp theo tỉ lệ sản phẩm đủ dữ liệu chủ",
      f: "Mỗi doanh nghiệp có sản phẩm: sản phẩm đủ dữ liệu chủ / tổng sản phẩm của doanh nghiệp; đếm doanh nghiệp theo khoảng tỉ lệ.",
      type: "bar",
      labels: ["< 40%", "40–59%", "60–79%", "80–99%", "100%"],
      ds: [["Doanh nghiệp", [58, 47, 62, 96, 112]]],
    },
    {
      id: "dn6",
      for: ["H1", "H2"],
      t: "Cơ cấu doanh nghiệp theo mức độ tham gia",
      f: "Phân loại tại cuối kỳ; cộng lại bằng Tổng số doanh nghiệp.",
      type: "pie",
      labels: [
        "Chưa có sản phẩm",
        "Có sản phẩm, chưa phát sinh chứng chỉ số",
        "Đã phát sinh chứng chỉ số sự kiện",
      ],
      ds: [["DN", [61, 50, 325]]],
    },
    {
      id: "dn5",
      for: ["H3"],
      t: "Doanh nghiệp và tỉ lệ UID đạt đủ công đoạn theo địa phương",
      f: "Cột: tổng doanh nghiệp của tỉnh (theo trụ sở chính). Đường: UID đạt đủ công đoạn / UID đã kích hoạt của doanh nghiệp trong tỉnh.",
      type: "combo",
      y2pct: 1,
      labels: ["Hà Nội", "TP.HCM", "Đà Nẵng", "Lâm Đồng", "Long An", "Cần Thơ"],
      ds: [
        ["Tổng doanh nghiệp", [124, 98, 46, 52, 61, 55]],
        ["Tỉ lệ UID đạt (%)", [78, 74, 72, 69, 63, 58], "line"],
      ],
    },
    {
      id: "dnW",
      t: "Cầu biến động doanh nghiệp hoạt động",
      f: "Đầu kỳ + doanh nghiệp mới bắt đầu hoạt động + doanh nghiệp quay lại − doanh nghiệp ngừng hoạt động = Cuối kỳ. Hoạt động = có chứng chỉ số trong 30 ngày.",
      type: "waterfall",
      for: ["H2", "H7"],
      steps: [
        ["Đầu kỳ (31/8)", 251, "total"],
        ["Mới hoạt động", 31],
        ["Quay lại", 12],
        ["Ngừng hoạt động", -30],
        ["Cuối kỳ (30/9)", 264, "total"],
      ],
    },
    {
      id: "dnC",
      t: "Tỉ lệ hoạt động theo tháng onboard (cohort)",
      f: "Mỗi dòng là nhóm doanh nghiệp onboard trong cùng tháng; ô = % doanh nghiệp của nhóm còn hoạt động sau N tháng.",
      type: "cohort",
      for: ["H6", "H8"],
      rows: [
        ["T4 (31)", [100, 74, 68, 65, 61, 58]],
        ["T5 (38)", [100, 79, 71, 66, 63]],
        ["T6 (44)", [100, 77, 72, 69]],
        ["T7 (52)", [100, 81, 75]],
        ["T8 (61)", [100, 83]],
        ["T9 (68)", [100]],
      ],
      cols: ["Tháng 0", "+1", "+2", "+3", "+4", "+5"],
    },
    {
      id: "dnU",
      t: "Tỉ lệ doanh nghiệp hoạt động theo đơn vị cung cấp giải pháp",
      f: "Doanh nghiệp hoạt động / Doanh nghiệp đã ủy quyền cho đơn vị.",
      type: "hbar",
      for: ["H2"],
      pct: 1,
      labels: ["Checkee", "TrangNTT", "ThanhTP", "Test Đại Lý 01", "P6_Thanh"],
      ds: [["Hoạt động", [82, 73, 67, 57, 39]]],
    },
    {
      id: "dnF",
      t: "Trường dữ liệu chủ hay thiếu ở doanh nghiệp chưa đủ",
      f: "Số doanh nghiệp có ≥ 1 sản phẩm thiếu trường, theo trường bắt buộc.",
      type: "hbar",
      for: ["H4"],
      labels: [
        "Hình ảnh",
        "Hồ sơ công bố",
        "Quy cách",
        "Hạn sử dụng",
        "Phân loại GPC",
      ],
      ds: [["Doanh nghiệp", [188, 142, 121, 96, 64]]],
    },
  ],
  warns: [
    {
      for: ["H3"],
      t: "Doanh nghiệp có tỉ lệ UID đạt đủ công đoạn giảm quá 10 điểm",
      sev: "critical",
      n: 14,
      cols: [
        "Doanh nghiệp",
        "Tháng trước",
        "Tháng này",
        "Công đoạn thiếu nhiều nhất",
      ],
      rows: [
        ["Thủy sản Cửu Long", "81%", "62%", "Xuất hàng"],
        ["Cty TP Hà Thành", "70%", "52%", "Sản xuất, chế biến"],
        ["Cty CP Chế biến Long An", "76%", "61%", "Tiếp nhận"],
      ],
    },
    {
      for: ["H4"],
      t: "Doanh nghiệp có trên 50% sản phẩm thiếu dữ liệu chủ",
      sev: "high",
      n: 58,
      cols: ["Doanh nghiệp", "Sản phẩm", "Thiếu dữ liệu chủ", "Tỉ lệ"],
      rows: [
        ["Masan", 1980, 612, "31%"],
        ["Cty TP Hà Thành", 96, 77, "80%"],
        ["Cty CP Tech Brand", 22, 15, "68%"],
        ["Cty TNHH MTV DV 5 Cua", 14, 9, "64%"],
      ],
    },
    {
      for: ["H1"],
      t: "Doanh nghiệp chưa có sản phẩm sau 30 ngày",
      sev: "medium",
      n: 47,
      cols: ["Doanh nghiệp", "Mã số thuế", "Ngày tạo", "Số ngày"],
      rows: [
        ["Cty TNHH Nông sản Việt Xanh", "0109876543", "12/06/2026", 115],
        ["HTX Chè Tân Cương", "4600512387", "03/07/2026", 94],
        ["Cty CP Thực phẩm Minh An", "0315678901", "28/07/2026", 69],
      ],
    },
    {
      for: ["H2", "H7", "H8"],
      t: "Doanh nghiệp không khai báo sự kiện quá 90 ngày",
      sev: "medium",
      n: 39,
      cols: ["Doanh nghiệp", "Sản phẩm", "Lần khai báo cuối", "Đơn vị"],
      rows: [
        ["Cty TNHH MTV DV 5 Cua", 14, "18/05/2026", "TrangNTT"],
        ["Cty CP Tech Brand", 22, "02/06/2026", "ThanhTP"],
        ["HTX Rau sạch Đông Anh", 9, "30/06/2026", "Checkee"],
      ],
    },
  ],
};
