import type { Mod } from "../types";

/** Quản trị hệ thống › Đơn vị cung cấp giải pháp (/quan-tri/doi-tac) */
export const doiTac: Mod = {
  k: "dt",
  g: "Quản trị hệ thống",
  t: "Đơn vị cung cấp giải pháp",
  d: "Hiệu quả kênh triển khai và đáp ứng tiêu chuẩn tích hợp",
  href: "/quan-tri/doi-tac",
  cards: [
    {
      id: "H1",
      l: "Tỉ lệ chuyển đổi doanh nghiệp",
      v: 280,
      t: 2.4,
      k: "core",
      d: 436,
      f: "Doanh nghiệp đã phát sinh chứng chỉ số sự kiện / Doanh nghiệp đã onboard qua đơn vị.",
      goal: 80,
    },
    {
      id: "H2",
      l: "Tỉ lệ đơn vị có doanh nghiệp hoạt động",
      v: 9,
      t: 12.5,
      k: "core",
      d: 23,
      f: "Đơn vị có ≥ 1 doanh nghiệp hoạt động / Tổng đơn vị.",
      goal: 80,
    },
    {
      id: "H3",
      l: "Tỉ lệ đơn vị gửi đúng chuẩn EPCIS 2.0",
      v: 14,
      t: 16.7,
      k: "core",
      d: 23,
      goal: 85,
    },
    {
      id: "H4",
      l: "Tỉ lệ chứng chỉ số bị từ chối",
      v: "1,1%",
      t: -6.3,
      k: "core",
      bad: 1,
      f: "Chứng chỉ số bị từ chối / Tổng chứng chỉ số gửi qua các đơn vị.",
    },
    { id: "H5", l: "Tổng số đơn vị", v: 23, t: 4.5, k: "scale", goalN: 30 },
    {
      id: "H6",
      l: "Doanh nghiệp onboard trong tháng",
      v: 68,
      t: 11.5,
      k: "scale",
    },
    {
      id: "H7",
      l: "Doanh nghiệp hoạt động qua đơn vị",
      v: 236,
      t: 7.8,
      k: "scale",
    },
    {
      id: "H8",
      l: "Đơn vị chưa có doanh nghiệp",
      v: 11,
      t: 0,
      k: "risk",
      bad: 1,
    },
  ],
  charts: [
    {
      id: "dt1",
      for: ["H3"],
      t: "Đơn vị đáp ứng tiêu chuẩn tích hợp",
      f: "Đơn vị đạt tiêu chí / Tổng số đơn vị cung cấp giải pháp (23).",
      type: "ratio",
      items: [
        ["Gửi sự kiện đúng chuẩn EPCIS 2.0", 14, 23],
        ["Ký bằng chứng số (VC) phía client", 11, 23],
        ["Tỉ lệ sự kiện bị từ chối < 2%", 9, 23],
        ["Đã có doanh nghiệp hoạt động", 12, 23],
      ],
    },
    {
      id: "dt2",
      for: ["H2", "H7", "H8"],
      t: "Doanh nghiệp theo đơn vị cung cấp giải pháp",
      f: "Doanh nghiệp đã ủy quyền cho từng đơn vị, tách hoạt động (khai báo trong 30 ngày) và không hoạt động.",
      type: "stack",
      labels: ["TrangNTT", "ThanhTP", "Test Đại Lý 01", "P6_Thanh", "Checkee"],
      ds: [
        ["Hoạt động", [94, 58, 31, 12, 41]],
        ["Không hoạt động", [34, 28, 23, 19, 9]],
      ],
    },
    {
      id: "dt3",
      for: ["H1"],
      t: "Tỉ lệ chuyển đổi doanh nghiệp của đơn vị cung cấp giải pháp",
      f: "Doanh nghiệp có khai báo sự kiện / Doanh nghiệp đơn vị đã onboard.",
      type: "hbar",
      pct: 1,
      labels: ["Checkee", "TrangNTT", "ThanhTP", "Test Đại Lý 01", "P6_Thanh"],
      ds: [["Chuyển đổi", [82, 73, 67, 57, 39]]],
    },
    {
      id: "dt4",
      for: ["H1", "H6"],
      t: "Doanh nghiệp onboard mới và tỉ lệ chuyển đổi",
      f: "Cột: doanh nghiệp tạo mới qua đơn vị cung cấp giải pháp trong tháng. Đường: Doanh nghiệp có khai báo sự kiện / Doanh nghiệp đã onboard (lũy kế).",
      type: "combo",
      y2pct: 1,
      labels: ["T4", "T5", "T6", "T7", "T8", "T9"],
      ds: [
        ["Onboard mới", [31, 38, 44, 52, 61, 68]],
        ["Tỉ lệ chuyển đổi (%)", [55, 57, 59, 61, 63, 64], "line"],
      ],
    },
    {
      id: "dt5",
      for: ["H5"],
      t: "Cơ cấu đơn vị cung cấp giải pháp theo loại hình",
      f: "Phân loại theo loại hình đơn vị cung cấp giải pháp khai báo khi đăng ký.",
      type: "pie",
      labels: [
        "Nền tảng truy xuất",
        "Đại lý triển khai",
        "Tích hợp ERP",
        "Đơn vị tư vấn",
      ],
      ds: [["Đơn vị", [6, 9, 4, 4]]],
    },
    {
      id: "dt6",
      for: ["H7"],
      t: "Doanh nghiệp hoạt động của các đơn vị cung cấp giải pháp chính",
      f: "Doanh nghiệp có khai báo trong 30 ngày, tại cuối mỗi tháng.",
      type: "line",
      labels: ["T4", "T5", "T6", "T7", "T8", "T9"],
      ds: [
        ["TrangNTT", [61, 67, 74, 81, 88, 94]],
        ["ThanhTP", [38, 42, 46, 50, 54, 58]],
        ["Checkee", [12, 18, 24, 31, 36, 41]],
      ],
    },
    {
      id: "dtC",
      t: "Tỉ lệ chuyển đổi theo tháng onboard (cohort)",
      f: "Mỗi dòng là nhóm doanh nghiệp onboard cùng tháng; ô = % đã phát sinh chứng chỉ số sau N tháng.",
      type: "cohort",
      for: ["H1"],
      rows: [
        ["T4 (31)", [29, 52, 61, 65, 68, 71]],
        ["T5 (38)", [34, 55, 63, 67, 70]],
        ["T6 (44)", [36, 58, 66, 69]],
        ["T7 (52)", [38, 61, 67]],
        ["T8 (61)", [41, 63]],
        ["T9 (68)", [44]],
      ],
      cols: ["Tháng 0", "+1", "+2", "+3", "+4", "+5"],
    },
    {
      id: "dtR",
      t: "Tỉ lệ chứng chỉ số bị từ chối theo đơn vị",
      f: "Chứng chỉ số bị từ chối / Chứng chỉ số gửi qua đơn vị.",
      type: "hbar",
      for: ["H4"],
      pct: 1,
      labels: ["Test Đại Lý 01", "P6_Thanh", "ThanhTP", "TrangNTT", "Checkee"],
      ds: [["Từ chối", [8.5, 6.5, 5.5, 1.8, 0.6]]],
    },
  ],
  warns: [
    {
      for: ["H8", "H1"],
      t: "Đơn vị chưa onboard doanh nghiệp quá 60 ngày",
      sev: "medium",
      n: 7,
      cols: ["Đơn vị", "Ngày tạo", "Số ngày"],
      rows: [
        ["dd", "02/05/2026", 156],
        ["xxx", "18/05/2026", 140],
        ["TrangNTT2", "30/06/2026", 97],
      ],
    },
    {
      for: ["H4", "H3"],
      t: "Đơn vị có tỉ lệ sự kiện bị từ chối trên 5%",
      sev: "high",
      n: 3,
      cols: ["Đơn vị", "Sự kiện", "Bị từ chối", "Tỉ lệ"],
      rows: [
        ["Test Đại Lý 01", 8420, 712, "8,5%"],
        ["P6_Thanh", 3110, 201, "6,5%"],
        ["ThanhTP", 21400, 1180, "5,5%"],
      ],
    },
    {
      for: ["H2", "H7"],
      t: "Đơn vị có trên 50% doanh nghiệp không hoạt động",
      sev: "medium",
      n: 2,
      cols: ["Đơn vị", "Doanh nghiệp", "Không hoạt động"],
      rows: [
        ["P6_Thanh", 31, "61%"],
        ["xxx", 3, "67%"],
      ],
    },
  ],
};
