import type { Mod } from "../types";

/** Danh mục hệ thống › Đơn vị hành chính (/danh-muc/don-vi-hanh-chinh) */
export const donViHanhChinh: Mod = {
  k: "hc",
  g: "Danh mục hệ thống",
  t: "Đơn vị hành chính",
  d: "Chất lượng danh mục đơn vị hành chính 2 cấp dùng chung cho địa chỉ cơ sở, phạm vi dữ liệu và thống kê theo địa phương",
  href: "/danh-muc/don-vi-hanh-chinh",
  cards: [
    {
      id: "H1",
      l: "Tỉ lệ cơ sở có mã hành chính chuẩn",
      v: 968,
      t: 0.9,
      k: "core",
      d: 1064,
      goal: 90,
    },
    {
      id: "H2",
      l: "Tỉ lệ cơ sở không dùng mã cũ",
      v: 1027,
      t: 2.4,
      k: "core",
      d: 1064,
      f: "Cơ sở không dùng mã tỉnh, xã trước sắp xếp / Tổng cơ sở.",
      goal: 90,
    },
    {
      id: "H3",
      l: "Tỉ lệ mã đồng bộ từ danh mục quốc gia",
      v: 3355,
      t: 0,
      k: "core",
      d: 3355,
      goal: 90,
    },
    {
      id: "H4",
      l: "Tỉ lệ thay đổi đã đồng bộ xuống cơ sở",
      v: 7,
      t: 16.7,
      k: "core",
      d: 12,
      f: "Thay đổi danh mục trong tháng đã cập nhật xong cho cơ sở bị ảnh hưởng / Thay đổi trong tháng.",
      goal: 80,
    },
    { id: "H5", l: "Tổng số tỉnh/thành", v: 34, t: 0, k: "scale" },
    { id: "H6", l: "Tổng số xã, phường, đặc khu", v: 3321, t: 0, k: "scale" },
    {
      id: "H7",
      l: "Xã, phường có cơ sở định danh",
      v: 1284,
      t: 6,
      k: "scale",
      goalN: 1500,
    },
    {
      id: "H8",
      l: "Tỉnh/thành có trên 20% cơ sở thiếu mã",
      v: 4,
      t: -20,
      k: "risk",
      bad: 1,
    },
  ],
  charts: [
    {
      id: "hc1",
      for: ["H1", "H2"],
      t: "Chất lượng mã đơn vị hành chính trên cơ sở, địa điểm",
      f: "Số cơ sở, địa điểm đạt tiêu chí / Tổng số cơ sở, địa điểm (1.064).",
      type: "ratio",
      items: [
        ["Có mã tỉnh chuẩn", 1012, 1064],
        ["Có mã xã, phường chuẩn", 968, 1064],
        ["Không dùng mã cũ trước sắp xếp", 1027, 1064],
      ],
    },
    {
      id: "hc2",
      for: ["H5", "H6"],
      t: "Cơ cấu đơn vị cấp xã",
      f: "Đếm đơn vị cấp xã theo loại trong danh mục.",
      type: "pie",
      labels: ["Xã", "Phường", "Đặc khu"],
      ds: [["Đơn vị", [2621, 687, 13]]],
    },
    {
      id: "hc3",
      for: ["H1", "H8"],
      t: "Cơ sở và tỉ lệ có mã chuẩn theo tỉnh/thành",
      f: "Cột: số cơ sở, địa điểm của tỉnh. Đường: cơ sở có mã xã, phường chuẩn / cơ sở của tỉnh.",
      type: "combo",
      y2pct: 1,
      labels: ["Hà Nội", "TP.HCM", "Long An", "Lâm Đồng", "Cần Thơ", "Đà Nẵng"],
      ds: [
        ["Cơ sở", [386, 241, 92, 71, 60, 51]],
        ["Có mã chuẩn (%)", [95, 74, 75, 90, 78, 92], "line"],
      ],
    },
    {
      id: "hc4",
      for: ["H2"],
      t: "Mã cũ chưa chuyển đổi theo tháng",
      f: "Số cơ sở, địa điểm còn dùng mã tỉnh, xã trước sắp xếp tại cuối mỗi tháng.",
      type: "line",
      labels: ["T4", "T5", "T6", "T7", "T8", "T9"],
      ds: [["Mã cũ", [214, 168, 121, 86, 50, 37]]],
    },
    {
      id: "hc5",
      for: ["H7"],
      t: "Xã, phường có cơ sở định danh theo tỉnh/thành",
      f: "Số xã, phường có ≥ 1 cơ sở, địa điểm định danh GLN; 6 tỉnh nhiều nhất.",
      type: "bar",
      labels: ["Hà Nội", "TP.HCM", "Long An", "Lâm Đồng", "Cần Thơ", "Đà Nẵng"],
      ds: [["Xã, phường", [126, 102, 58, 47, 39, 31]]],
    },
    {
      id: "hcS",
      t: "Thay đổi danh mục theo tháng",
      f: "Thay đổi đơn vị hành chính có hiệu lực trong tháng; tách đã và chưa đồng bộ xuống cơ sở, địa điểm.",
      type: "stack",
      for: ["H3", "H4"],
      labels: ["T4", "T5", "T6", "T7", "T8", "T9"],
      ds: [
        ["Đã đồng bộ", [18, 25, 14, 9, 15, 7]],
        ["Chưa đồng bộ", [0, 0, 1, 0, 2, 5]],
      ],
    },
  ],
  warns: [
    {
      for: ["H2"],
      t: "Mã cũ chưa chuyển đổi đang được sử dụng",
      sev: "high",
      n: 37,
      cols: [
        "Cơ sở, địa điểm",
        "Mã đang dùng",
        "Mã mới đề xuất",
        "Tổ chức, cá nhân",
      ],
      rows: [
        ["Kho Bình Chánh", "Xã Bình Chánh (cũ)", "Xã Bình Chánh", "Masan"],
        [
          "Cơ sở Hà Nội",
          "Quận Hoàng Mai (cũ)",
          "Phường Hoàng Mai",
          "Doanh nghiệp",
        ],
        [
          "Vùng trồng Mộc Châu 02",
          "Huyện Mộc Châu (cũ)",
          "Xã Mộc Châu",
          "HTX Chè Mộc Châu",
        ],
      ],
    },
    {
      for: ["H1", "H8"],
      t: "Tỉnh/thành có trên 20% cơ sở thiếu mã hành chính",
      sev: "medium",
      n: 4,
      cols: ["Tỉnh/thành", "Cơ sở", "Thiếu mã", "Tỉ lệ"],
      rows: [
        ["TP.HCM", 241, 62, "26%"],
        ["Long An", 92, 23, "25%"],
        ["Cần Thơ", 60, 13, "22%"],
      ],
    },
    {
      for: ["H4"],
      t: "Thay đổi danh mục chưa đồng bộ xuống cơ sở, địa điểm",
      sev: "medium",
      n: 5,
      cols: ["Đơn vị", "Thay đổi", "Ngày hiệu lực", "Cơ sở bị ảnh hưởng"],
      rows: [
        ["Phường Hoàng Mai", "Đổi tên", "01/09/2026", 14],
        ["Xã Mộc Châu", "Hợp nhất", "15/09/2026", 6],
      ],
    },
  ],
};
