import type { Mod } from "../types";

/** Truy xuất nguồn gốc › Giấy tờ, chứng nhận (/chung-nhan-attp/danh-sach) */
export const giayChungNhan: Mod = {
  k: "cc",
  g: "Truy xuất nguồn gốc",
  t: "Giấy tờ, chứng nhận",
  d: "Vòng đời và mức độ đáp ứng điều kiện chứng nhận",
  href: "/chung-nhan-attp/danh-sach",
  cards: [
    {
      id: "H1",
      l: "Tổng số giấy tờ, chứng nhận",
      v: 754,
      t: 5.6,
      k: "scale",
      f: "= Do cơ quan, tổ chức cấp (566) + Tổ chức, cá nhân tự công bố (188).",
      goalN: 800,
    },
    {
      id: "H2",
      l: "Cấp mới trong tháng",
      v: 62,
      t: 12.7,
      k: "scale",
      f: "Gồm cơ quan, tổ chức cấp (41) và tự công bố (21).",
    },
    {
      id: "H3",
      l: "Do cơ quan, tổ chức cấp",
      v: 566,
      t: 4.6,
      k: "scale",
      f: "Cơ quan nhà nước (Cấp 2) và tổ chức chứng nhận cấp.",
    },
    { id: "H4", l: "Tổ chức, cá nhân tự công bố", v: 188, t: 6.8, k: "scale" },
    {
      id: "H5",
      l: "Đối tượng diện bắt buộc có giấy tờ còn hiệu lực",
      v: 2611,
      t: 3,
      k: "core",
      d: 3905,
      f: "(Cơ sở diện bắt buộc có chứng nhận ATTP + Sản phẩm diện công bố có hồ sơ) còn hiệu lực / Tổng đối tượng thuộc diện bắt buộc.",
      goal: 85,
    },
    {
      id: "H6",
      l: "Sắp hết hiệu lực (≤ 30 ngày)",
      v: 23,
      t: 27.8,
      k: "risk",
      bad: 1,
    },
    { id: "H7", l: "Đã hết hiệu lực", v: 41, t: 7.9, k: "risk", bad: 1 },
    { id: "H8", l: "Đã thu hồi trong tháng", v: 3, t: 50, k: "risk", bad: 1 },
  ],
  charts: [
    {
      id: "cc1",
      for: ["H5"],
      t: "Đối tượng thuộc diện bắt buộc có giấy tờ, chứng nhận còn hiệu lực",
      f: "Đối tượng thuộc diện bắt buộc có giấy tờ, chứng nhận tương ứng còn hiệu lực / Tổng đối tượng thuộc diện bắt buộc.",
      type: "ratio",
      items: [
        ["Cơ sở có chứng nhận ATTP", 531, 720],
        ["Sản phẩm có hồ sơ công bố", 2080, 3185],
        ["Doanh nghiệp có ≥ 1 giấy tờ, chứng nhận", 268, 436],
      ],
    },
    {
      id: "cc2",
      for: ["H5", "H7"],
      t: "Vòng đời giấy tờ, chứng nhận",
      f: "Phân loại theo trạng thái tại cuối kỳ.",
      type: "pie",
      labels: [
        "Còn hiệu lực",
        "Sắp hết hiệu lực ≤ 30 ngày",
        "Đã hết hiệu lực",
        "Đã thu hồi",
      ],
      ds: [["CC", [665, 23, 41, 25]]],
    },
    {
      id: "cc3",
      for: ["H1", "H3", "H4"],
      t: "Giấy tờ, chứng nhận theo loại và nguồn cấp",
      f: "Đếm giấy tờ, chứng nhận còn hiệu lực theo loại; tách cơ quan nhà nước cấp, tổ chức chứng nhận cấp và tổ chức, cá nhân tự công bố.",
      type: "stack",
      labels: [
        "Đủ ĐK ATTP",
        "Công bố SP",
        "FSSC 22000",
        "VietGAP",
        "GlobalGAP",
      ],
      ds: [
        ["Cơ quan nhà nước cấp", [142, 0, 0, 38, 0]],
        ["Tổ chức chứng nhận cấp", [0, 0, 214, 58, 96]],
        ["Tổ chức, cá nhân tự công bố", [0, 188, 0, 0, 0]],
      ],
    },
    {
      id: "cc4",
      for: ["H2"],
      t: "Giấy tờ, chứng nhận cấp mới và tỉ lệ còn hiệu lực",
      f: "Cột: giấy tờ, chứng nhận cấp mới theo ngày cấp. Đường: Giấy tờ, chứng nhận còn hiệu lực / Tổng giấy tờ, chứng nhận tại cuối tháng.",
      type: "combo",
      y2pct: 1,
      labels: ["T4", "T5", "T6", "T7", "T8", "T9"],
      ds: [
        ["Cấp mới", [38, 44, 51, 47, 55, 62]],
        ["Tỉ lệ còn hiệu lực (%)", [93, 92, 93, 91, 92, 91], "line"],
      ],
    },
    {
      id: "cc5",
      for: ["H6"],
      t: "Dự báo giấy tờ, chứng nhận hết hiệu lực 6 tháng tới",
      f: "Đếm giấy tờ, chứng nhận còn hiệu lực theo tháng của ngày hết hiệu lực.",
      type: "bar",
      labels: ["T10", "T11", "T12", "T1", "T2", "T3"],
      ds: [["Giấy tờ, chứng nhận", [23, 31, 18, 42, 27, 36]]],
    },
    {
      id: "cc6",
      for: ["H5"],
      t: "Đối tượng diện bắt buộc có giấy tờ, chứng nhận theo tháng",
      f: "Đối tượng thuộc diện bắt buộc có giấy tờ, chứng nhận còn hiệu lực / Tổng đối tượng thuộc diện bắt buộc, tại cuối tháng.",
      type: "line",
      pct: 1,
      labels: ["T4", "T5", "T6", "T7", "T8", "T9"],
      ds: [
        ["Cơ sở có chứng nhận ATTP", [66, 68, 69, 71, 72, 74]],
        ["Sản phẩm có hồ sơ công bố", [52, 55, 57, 60, 62, 65]],
      ],
    },
    {
      id: "ccG",
      t: "Hồ sơ tự công bố theo phân loại GPC",
      f: "Số hồ sơ tự công bố còn hiệu lực theo GPC – Segment.",
      type: "hbar",
      for: ["H4"],
      labels: ["Thực phẩm chế biến", "Bánh kẹo", "Sữa & chế phẩm", "Thủy sản"],
      ds: [["Hồ sơ", [82, 51, 34, 21]]],
    },
    {
      id: "ccX",
      t: "Đã hết hiệu lực theo loại",
      f: "Giấy tờ, chứng nhận đã hết hiệu lực chưa gia hạn, theo loại.",
      type: "hbar",
      for: ["H7"],
      labels: ["VietGAP", "Đủ ĐK ATTP", "GlobalGAP", "FSSC 22000"],
      ds: [["Giấy tờ", [14, 13, 8, 6]]],
    },
    {
      id: "ccR",
      t: "Lý do thu hồi",
      f: "Giấy tờ, chứng nhận bị thu hồi trong 6 tháng, theo lý do.",
      type: "pie",
      for: ["H8"],
      labels: [
        "Vi phạm khi hậu kiểm",
        "Cơ sở ngừng hoạt động",
        "Hồ sơ sai",
        "Doanh nghiệp đề nghị",
      ],
      ds: [["Giấy tờ", [11, 7, 4, 3]]],
    },
  ],
  warns: [
    {
      for: ["H5", "H6"],
      t: "Giấy tờ, chứng nhận sắp hết hiệu lực trong 30 ngày",
      sev: "high",
      n: 23,
      cols: [
        "Số chứng nhận",
        "Loại giấy tờ, chứng nhận",
        "Đối tượng",
        "Hết hiệu lực",
      ],
      rows: [
        ["CERT-ATTP-0412", "Đủ ĐK ATTP", "Bếp ăn KCN Đức Hòa", "09/10/2026"],
        ["CERT-119-0003", "GlobalGAP", "Cty TNHH DV Di Vina", "18/10/2026"],
        ["CERT-109-00001", "FSSC 22000", "Bánh quy bơ Pháp", "27/10/2026"],
      ],
    },
    {
      for: ["H5", "H7"],
      t: "Giấy tờ, chứng nhận đã hết hiệu lực, đối tượng vẫn đang hoạt động",
      sev: "critical",
      n: 38,
      cols: [
        "Số chứng nhận",
        "Loại giấy tờ, chứng nhận",
        "Đối tượng",
        "Hết hiệu lực từ",
      ],
      rows: [
        ["CERT-1009-001", "FSSC 22000", "Bánh quy bơ Pháp", "01/01/2026"],
        ["CERT-ATTP-0188", "Đủ ĐK ATTP", "Kho lạnh Cái Răng", "15/07/2026"],
        ["CERT-VG-0921", "VietGAP", "Vùng trồng Mộc Châu 02", "30/08/2026"],
      ],
    },
    {
      for: ["H1", "H3", "H4"],
      t: "Giấy tờ, chứng nhận thiếu thông tin bắt buộc",
      sev: "medium",
      n: 117,
      cols: ["Số chứng nhận", "Loại", "Thiếu", "Người nhập liệu"],
      rows: [
        ["CERT-119-0003", "GlobalGAP", "Doanh nghiệp", "TrangNTT"],
        ["CERT_119_0001", "Sở hữu trí tuệ", "Doanh nghiệp, cơ sở", "TrangNTT"],
        ["CERT-992026-001", "FSSC 22000", "Đơn vị cấp hợp lệ", "ThanhTP"],
      ],
    },
  ],
};
