import type { Mod } from "../types";

/** Quản lý ATTP › Hồ sơ tự công bố (/tu-cong-bo/danh-sach) */
export const hoSoTuCongBo: Mod = {
  k: "tcb",
  g: "Quản lý ATTP",
  t: "Hồ sơ tự công bố",
  d: "Hồ sơ tự công bố sản phẩm thực phẩm theo Nghị định 15/2018/NĐ-CP",
  href: "/tu-cong-bo/danh-sach",
  cards: [
    {
      id: "H1",
      l: "Tỉ lệ hồ sơ hợp lệ ngay lần đầu",
      v: 842,
      t: 2.6,
      k: "core",
      d: 1036,
      f: "Hồ sơ tiếp nhận không phải yêu cầu bổ sung / Tổng hồ sơ tiếp nhận trong kỳ.",
    },
    {
      id: "H2",
      l: "Tỉ lệ hồ sơ có phiếu kiểm nghiệm còn hạn",
      v: 961,
      t: 1.4,
      k: "core",
      d: 1036,
      f: "Hồ sơ có phiếu kết quả kiểm nghiệm trong 12 tháng / Tổng hồ sơ.",
    },
    {
      id: "H3",
      l: "Tỉ lệ sản phẩm TXNG đã liên kết hồ sơ tự công bố",
      v: 1184,
      t: 5.8,
      k: "core",
      d: 1720,
      f: "Sản phẩm (GTIN) thuộc diện tự công bố đã gắn số hồ sơ / Sản phẩm thuộc diện tự công bố.",
    },
    {
      id: "H4",
      l: "Tỉ lệ hồ sơ được hậu kiểm",
      v: 118,
      t: 3.1,
      k: "core",
      d: 1036,
      f: "Hồ sơ đã được cơ quan quản lý hậu kiểm / Tổng hồ sơ tiếp nhận trong năm.",
    },
    { id: "H5", l: "Tổng hồ sơ đã tiếp nhận", v: 1036, t: 4.2, k: "scale" },
    { id: "H6", l: "Hồ sơ mới trong tháng", v: 96, t: 7.9, k: "scale" },
    {
      id: "H7",
      l: "Hồ sơ hậu kiểm phát hiện vi phạm",
      v: 14,
      t: 16.7,
      k: "risk",
      bad: 1,
    },
    {
      id: "H8",
      l: "Sản phẩm lưu hành chưa có hồ sơ",
      v: 536,
      t: -6.3,
      k: "risk",
      bad: 1,
    },
  ],
  charts: [
    {
      id: "tcb1",
      for: ["H1", "H2", "H3"],
      t: "Mức độ đầy đủ của hồ sơ tự công bố",
      f: "Số hồ sơ đạt từng tiêu chí / Tổng hồ sơ (1.036).",
      type: "ratio",
      items: [
        ["Hợp lệ ngay lần đầu", 842, 1036],
        ["Có phiếu kiểm nghiệm còn hạn", 961, 1036],
        ["Có nhãn sản phẩm đính kèm", 988, 1036],
        ["Đã liên kết sản phẩm TXNG", 774, 1036],
      ],
    },
    {
      id: "tcb2",
      for: ["H5", "H6"],
      t: "Hồ sơ tiếp nhận theo tháng",
      f: "Số hồ sơ tiếp nhận mới trong tháng; tách hợp lệ và phải bổ sung.",
      type: "stack",
      labels: ["T4", "T5", "T6", "T7", "T8", "T9"],
      ds: [
        ["Hợp lệ", [61, 68, 72, 70, 79, 81]],
        ["Phải bổ sung", [19, 17, 16, 18, 14, 15]],
      ],
    },
    {
      id: "tcb3",
      for: ["H5"],
      t: "Cơ cấu hồ sơ theo nhóm sản phẩm",
      f: "Đếm hồ sơ theo nhóm sản phẩm chính.",
      type: "pie",
      labels: [
        "Thực phẩm chế biến",
        "Đồ uống",
        "Phụ gia thực phẩm",
        "Dụng cụ, bao bì",
        "Khác",
      ],
      ds: [["Hồ sơ", [412, 236, 148, 131, 109]]],
    },
    {
      id: "tcb4",
      for: ["H4", "H7"],
      t: "Hậu kiểm và vi phạm theo địa phương",
      f: "Cột: số hồ sơ được hậu kiểm. Đường: tỉ lệ hồ sơ hậu kiểm phát hiện vi phạm.",
      type: "combo",
      y2pct: 1,
      labels: ["Hà Nội", "TP.HCM", "Đà Nẵng", "Lâm Đồng", "Long An", "Cần Thơ"],
      ds: [
        ["Hồ sơ hậu kiểm", [38, 31, 14, 12, 13, 10]],
        ["Tỉ lệ vi phạm (%)", [8, 13, 7, 17, 15, 10], "line"],
      ],
    },
    {
      id: "tcb5",
      for: ["H1"],
      t: "Lý do yêu cầu bổ sung hồ sơ",
      f: "Số hồ sơ phải bổ sung theo lý do (một hồ sơ có thể nhiều lý do).",
      type: "hbar",
      labels: [
        "Phiếu kiểm nghiệm thiếu chỉ tiêu",
        "Nhãn không đúng quy định",
        "Thiếu chỉ tiêu an toàn",
        "Sai thông tin tổ chức",
        "Hết hạn kiểm nghiệm",
      ],
      ds: [["Hồ sơ", [82, 64, 41, 28, 19]]],
    },
  ],
  warns: [
    {
      t: "Sản phẩm đang lưu hành có phiếu kiểm nghiệm quá 12 tháng",
      sev: "high",
      n: 75,
      cols: ["Sản phẩm", "Tổ chức, cá nhân", "Số hồ sơ", "Ngày kiểm nghiệm"],
      rows: [
        [
          "Nước mắm cá cơm 40N",
          "Cty TNHH Hưng Thành",
          "12/2025/HT-TCB",
          "04/08/2025",
        ],
        [
          "Bánh đậu xanh Rồng Vàng",
          "Cty CP Bảo Hiên",
          "07/2025/BH-TCB",
          "19/07/2025",
        ],
        [
          "Trà xanh túi lọc",
          "HTX Chè Tân Cương",
          "03/2025/TC-TCB",
          "02/06/2025",
        ],
      ],
      for: ["H2"],
    },
    {
      t: "Hồ sơ hậu kiểm phát hiện chỉ tiêu không đạt",
      sev: "critical",
      n: 14,
      cols: ["Sản phẩm", "Chỉ tiêu không đạt", "Đơn vị hậu kiểm", "Ngày"],
      rows: [
        [
          "Xúc xích tiệt trùng",
          "Nitrit vượt ngưỡng",
          "Chi cục ATVSTP Hà Nội",
          "22/09/2026",
        ],
        [
          "Nước giải khát có ga",
          "Tổng số vi sinh vật",
          "Sở Y tế TP.HCM",
          "15/09/2026",
        ],
        ["Mì sợi khô", "Chì (Pb)", "Sở Y tế Lâm Đồng", "09/09/2026"],
      ],
      for: ["H4", "H7"],
    },
    {
      t: "Sản phẩm có mã GTIN lưu hành nhưng chưa có hồ sơ tự công bố",
      sev: "medium",
      n: 536,
      cols: ["Sản phẩm", "GTIN", "Doanh nghiệp", "Ngày khai báo"],
      rows: [
        [
          "Cà phê rang xay 500g",
          "8936012345678",
          "Cty CP Cà phê Lâm Đồng",
          "11/07/2026",
        ],
        [
          "Mật ong rừng 250ml",
          "8936098765432",
          "HTX Ong mật Kon Tum",
          "26/07/2026",
        ],
      ],
      for: ["H3", "H8"],
    },
  ],
};
