import type { Mod } from "../types";

/** Quản lý ATTP › Kiểm tra ATTP (/kiem-tra) */
export const kiemTraAttp: Mod = {
  k: "kt",
  g: "Quản lý ATTP",
  t: "Kiểm tra ATTP",
  d: "Kế hoạch và kết quả kiểm tra, thanh tra an toàn thực phẩm",
  href: "/kiem-tra",
  cards: [
    {
      id: "H1",
      l: "Tỉ lệ hoàn thành kế hoạch kiểm tra",
      v: 612,
      t: 4.5,
      k: "core",
      d: 780,
      f: "Cuộc kiểm tra đã thực hiện / Cuộc kiểm tra theo kế hoạch năm (lũy kế đến kỳ).",
    },
    {
      id: "H2",
      l: "Tỉ lệ cơ sở được kiểm tra đạt yêu cầu",
      v: 2846,
      t: 1.8,
      k: "core",
      d: 3212,
      f: "Lượt cơ sở kiểm tra đạt / Tổng lượt cơ sở được kiểm tra.",
    },
    {
      id: "H3",
      l: "Tỉ lệ vi phạm đã xử lý xong",
      v: 281,
      t: 6.2,
      k: "core",
      d: 366,
      f: "Vi phạm đã ra quyết định và hoàn tất khắc phục / Tổng vi phạm phát hiện.",
    },
    {
      id: "H4",
      l: "Tỉ lệ biên bản số hóa trên hệ thống",
      v: 2704,
      t: 9.4,
      k: "core",
      d: 3212,
      f: "Biên bản kiểm tra được nhập trên hệ thống / Tổng lượt kiểm tra.",
    },
    { id: "H5", l: "Cuộc kiểm tra đã thực hiện", v: 612, t: 5.1, k: "scale" },
    {
      id: "H6",
      l: "Lượt cơ sở kiểm tra trong tháng",
      v: 418,
      t: 12,
      k: "scale",
    },
    {
      id: "H7",
      l: "Vi phạm quá hạn khắc phục",
      v: 42,
      t: 10.5,
      k: "risk",
      bad: 1,
    },
    { id: "H8", l: "Tổng tiền phạt (triệu đồng)", v: 1864, t: 7.3, k: "risk" },
  ],
  charts: [
    {
      id: "kt1",
      for: ["H1"],
      t: "Tiến độ kế hoạch kiểm tra theo đơn vị",
      f: "Cuộc kiểm tra đã thực hiện / Cuộc kiểm tra theo kế hoạch của đơn vị.",
      type: "hbar",
      pct: 1,
      labels: [
        "Chi cục ATVSTP",
        "Đội QLTT số 1",
        "Sở NN&MT",
        "Sở Công Thương",
        "UBND cấp xã",
      ],
      ds: [["Hoàn thành", [88, 81, 76, 69, 54]]],
    },
    {
      id: "kt2",
      for: ["H2", "H5"],
      t: "Kết quả kiểm tra theo tháng",
      f: "Lượt cơ sở được kiểm tra trong tháng; tách đạt và không đạt.",
      type: "stack",
      labels: ["T4", "T5", "T6", "T7", "T8", "T9"],
      ds: [
        ["Đạt", [402, 445, 468, 489, 512, 530]],
        ["Không đạt", [61, 58, 66, 57, 63, 61]],
      ],
    },
    {
      id: "kt3",
      for: ["H2"],
      t: "Nhóm vi phạm thường gặp",
      f: "Số lượt vi phạm theo nhóm hành vi theo Nghị định 115/2018/NĐ-CP.",
      type: "hbar",
      labels: [
        "Điều kiện vệ sinh cơ sở",
        "Không có giấy chứng nhận ATTP",
        "Ghi nhãn không đúng",
        "Không khám sức khỏe, tập huấn",
        "Sử dụng phụ gia ngoài danh mục",
      ],
      ds: [["Vi phạm", [124, 86, 71, 52, 33]]],
    },
    {
      id: "kt4",
      for: ["H3", "H7"],
      t: "Vi phạm theo tình trạng xử lý",
      f: "Phân loại tại cuối kỳ; cộng lại bằng tổng vi phạm phát hiện.",
      type: "pie",
      labels: [
        "Đã xử lý xong",
        "Đang khắc phục trong hạn",
        "Quá hạn khắc phục",
      ],
      ds: [["Vi phạm", [281, 43, 42]]],
    },
    {
      id: "kt5",
      for: ["H4"],
      t: "Số hóa biên bản kiểm tra theo tháng",
      f: "Biên bản nhập trên hệ thống / Tổng lượt kiểm tra trong tháng.",
      type: "line",
      pct: 1,
      labels: ["T4", "T5", "T6", "T7", "T8", "T9"],
      ds: [["Đã số hóa (%)", [61, 66, 72, 77, 81, 84]]],
    },
  ],
  warns: [
    {
      t: "Vi phạm quá hạn khắc phục chưa tái kiểm tra",
      sev: "critical",
      n: 42,
      cols: ["Cơ sở", "Hành vi vi phạm", "Hạn khắc phục", "Quá hạn (ngày)"],
      rows: [
        [
          "Bếp ăn tập thể KCN Thăng Long",
          "Điều kiện vệ sinh",
          "15/08/2026",
          53,
        ],
        ["Cơ sở giò chả Hữu Hòa", "Phụ gia ngoài danh mục", "30/08/2026", 38],
        ["Nhà hàng Hải Đăng", "Không có giấy chứng nhận", "05/09/2026", 32],
      ],
      for: ["H3", "H7"],
    },
    {
      t: "Đơn vị chậm tiến độ kế hoạch kiểm tra trên 20%",
      sev: "high",
      n: 6,
      cols: ["Đơn vị", "Kế hoạch", "Đã thực hiện", "Tỉ lệ"],
      rows: [
        ["UBND xã Sóc Sơn", 24, 9, "38%"],
        ["UBND phường Hoàng Mai", 18, 8, "44%"],
        ["Đội QLTT số 7", 30, 16, "53%"],
      ],
      for: ["H1"],
    },
    {
      t: "Lượt kiểm tra chưa nhập biên bản sau 7 ngày",
      sev: "medium",
      n: 508,
      cols: ["Cuộc kiểm tra", "Đơn vị", "Ngày kiểm tra", "Số cơ sở"],
      rows: [
        ["KT liên ngành Tết Trung thu", "Chi cục ATVSTP", "12/09/2026", 46],
        ["Kiểm tra bếp ăn trường học", "Phòng Y tế quận", "18/09/2026", 21],
      ],
      for: ["H4"],
    },
  ],
};
