import type { Mod } from "../types";

/** Truy xuất nguồn gốc › Lô sản phẩm (/truy-xuat/lo-san-pham) */
export const loSanPham: Mod = {
  k: "lo",
  g: "Truy xuất nguồn gốc",
  t: "Lô sản phẩm",
  d: "Lô sản xuất, lô hàng được khai báo và gắn bằng chứng số truy xuất",
  href: "/truy-xuat/lo-san-pham",
  cards: [
    {
      id: "H1",
      l: "Tỉ lệ lô đủ thông tin bắt buộc",
      v: 8124,
      t: 2.9,
      k: "core",
      d: 9310,
      f: "Lô có đủ ngày sản xuất, hạn sử dụng, cơ sở sản xuất và số lượng / Tổng lô.",
    },
    {
      id: "H2",
      l: "Tỉ lệ lô đã gán UID",
      v: 7442,
      t: 4.6,
      k: "core",
      d: 9310,
      f: "Lô có ≥ 1 UID kích hoạt / Tổng lô.",
    },
    {
      id: "H3",
      l: "Tỉ lệ lô có chứng chỉ số sự kiện đầy đủ",
      v: 6015,
      t: 3.8,
      k: "core",
      d: 9310,
      f: "Lô có đủ sự kiện theo quy trình tiêu chuẩn TXNG / Tổng lô.",
    },
    {
      id: "H4",
      l: "Tỉ lệ lô có kết quả kiểm nghiệm",
      v: 3910,
      t: 6.4,
      k: "core",
      d: 9310,
      f: "Lô đính kèm phiếu kết quả kiểm nghiệm / Tổng lô.",
    },
    { id: "H5", l: "Tổng số lô", v: 9310, t: 7.2, k: "scale" },
    { id: "H6", l: "Lô mới trong tháng", v: 1284, t: 10.3, k: "scale" },
    {
      id: "H7",
      l: "Lô hết hạn sử dụng vẫn còn UID lưu hành",
      v: 63,
      t: -12.5,
      k: "risk",
      bad: 1,
    },
    { id: "H8", l: "Lô bị thu hồi", v: 5, t: 25, k: "risk", bad: 1 },
  ],
  charts: [
    {
      id: "lo1",
      for: ["H1", "H2", "H3", "H4"],
      t: "Mức độ hoàn thiện dữ liệu lô",
      f: "Số lô đạt từng tiêu chí / Tổng lô (9.310).",
      type: "ratio",
      items: [
        ["Đủ thông tin bắt buộc", 8124, 9310],
        ["Đã gán UID", 7442, 9310],
        ["Đủ chứng chỉ số sự kiện", 6015, 9310],
        ["Có kết quả kiểm nghiệm", 3910, 9310],
      ],
    },
    {
      id: "lo2",
      for: ["H5", "H6"],
      t: "Lô khai báo mới theo tháng",
      f: "Số lô khai báo trong tháng, tách theo kênh khai báo.",
      type: "stack",
      labels: ["T4", "T5", "T6", "T7", "T8", "T9"],
      ds: [
        ["Qua API đơn vị giải pháp", [612, 688, 742, 801, 866, 914]],
        ["Nhập trên CMS", [251, 264, 288, 302, 331, 370]],
      ],
    },
    {
      id: "lo3",
      for: ["H3"],
      t: "Tỉ lệ lô đủ sự kiện theo nhóm sản phẩm",
      f: "Lô đủ chứng chỉ số sự kiện / Lô của nhóm.",
      type: "hbar",
      pct: 1,
      labels: [
        "Sữa & chế phẩm",
        "Thực phẩm chế biến",
        "Thủy sản",
        "Nông sản tươi",
        "Dược liệu",
      ],
      ds: [["Đủ sự kiện", [86, 71, 64, 58, 49]]],
    },
    {
      id: "lo4",
      for: ["H7", "H8"],
      t: "Tình trạng lô theo hạn sử dụng",
      f: "Phân loại lô tại cuối kỳ.",
      type: "pie",
      labels: [
        "Còn hạn > 3 tháng",
        "Còn hạn ≤ 3 tháng",
        "Đã hết hạn",
        "Đã thu hồi",
      ],
      ds: [["Lô", [6720, 1388, 1197, 5]]],
    },
  ],
  warns: [
    {
      t: "Lô đã hết hạn sử dụng nhưng UID vẫn được quét tại điểm bán",
      sev: "critical",
      n: 63,
      cols: ["Lô", "Sản phẩm", "Hạn sử dụng", "Lượt quét sau hạn"],
      rows: [
        ["L2603-118", "Sữa chua uống 180ml", "30/08/2026", 142],
        ["L2602-044", "Xúc xích tiệt trùng", "15/09/2026", 37],
        ["L2601-207", "Bánh quy bơ", "20/09/2026", 12],
      ],
      for: ["H7", "H8"],
    },
    {
      t: "Lô khai báo thiếu cơ sở sản xuất (GLN)",
      sev: "high",
      n: 412,
      cols: ["Lô", "Sản phẩm", "Doanh nghiệp", "Ngày khai báo"],
      rows: [
        [
          "L2609-031",
          "Cà phê rang xay",
          "Cty CP Cà phê Lâm Đồng",
          "22/09/2026",
        ],
        ["L2609-012", "Mật ong rừng", "HTX Ong mật Kon Tum", "18/09/2026"],
      ],
      for: ["H1"],
    },
    {
      t: "Lô chưa gán UID sau 14 ngày",
      sev: "medium",
      n: 1868,
      cols: ["Lô", "Sản phẩm", "Doanh nghiệp", "Số ngày"],
      rows: [
        ["L2609-004", "Nước mắm 40N", "Cty TNHH Hưng Thành", 21],
        ["L2608-118", "Gạo ST25", "HTX Sóc Trăng", 33],
      ],
      for: ["H2"],
    },
  ],
};
