import type { Mod } from "../types";

/** Danh mục hệ thống › Loại giấy tờ, chứng nhận (/danh-muc/loai-chung-chi) */
export const loaiChungChi: Mod = {
  k: "lcc",
  g: "Danh mục hệ thống",
  t: "Loại giấy tờ, chứng nhận",
  d: "Chất lượng danh mục loại giấy tờ, chứng nhận và mức độ sử dụng",
  href: "/danh-muc/loai-chung-chi",
  cards: [
    {
      id: "H1",
      l: "Tỉ lệ loại đủ thông tin danh mục",
      v: 4,
      t: 33.3,
      k: "core",
      d: 26,
      f: "Có mã nghiệp vụ, cơ quan có thẩm quyền cấp, thời hạn chuẩn / Tổng loại.",
      goal: 80,
    },
    {
      id: "H2",
      l: "Tỉ lệ loại được sử dụng",
      v: 12,
      t: 9.1,
      k: "core",
      d: 26,
      goal: 80,
    },
    {
      id: "H3",
      l: "Tỉ lệ loại có nguồn cấp",
      v: 19,
      t: 5.6,
      k: "core",
      d: 26,
      goal: 85,
    },
    {
      id: "H4",
      l: "Tỉ lệ hết hiệu lực, thu hồi",
      v: 66,
      t: 3.1,
      k: "core",
      d: 754,
      bad: 1,
      f: "Giấy tờ, chứng nhận đã hết hiệu lực hoặc đã thu hồi / Tổng giấy tờ, chứng nhận.",
    },
    { id: "H5", l: "Tổng số loại", v: 26, t: 4, k: "scale" },
    {
      id: "H6",
      l: "Giấy tờ phát sinh trong tháng",
      v: 62,
      t: 12.7,
      k: "scale",
    },
    { id: "H7", l: "Loại nghi trùng lặp", v: 3, t: 0, k: "risk", bad: 1 },
    { id: "H8", l: "Loại chưa sử dụng", v: 14, t: 0, k: "risk", bad: 1 },
  ],
  charts: [
    {
      id: "lcc1",
      for: ["H1", "H7"],
      t: "Danh mục đáp ứng chuẩn dữ liệu chủ",
      f: "Số loại đạt tiêu chí / Tổng số loại (26).",
      type: "ratio",
      items: [
        ["Có cơ quan quản lý", 17, 26],
        ["Có thời hạn hiệu lực chuẩn", 15, 26],
        ["Có liên kết tiêu chuẩn gốc", 11, 26],
        ["Có mã nghiệp vụ đọc được", 4, 26],
      ],
    },
    {
      id: "lcc2",
      for: ["H2", "H8"],
      t: "Số giấy tờ, chứng nhận theo loại",
      f: "Đếm giấy tờ, chứng nhận (mọi trạng thái) theo loại giấy tờ, chứng nhận, 6 loại nhiều nhất.",
      type: "hbar",
      labels: [
        "FSSC 22000",
        "Công bố sản phẩm",
        "Giấy chứng nhận ATTP",
        "GlobalGAP",
        "VietGAP",
        "Sở hữu trí tuệ",
      ],
      ds: [["Giấy tờ, chứng nhận", [214, 188, 142, 96, 58, 30]]],
    },
    {
      id: "lcc3",
      for: ["H3", "H5"],
      t: "Loại giấy tờ, chứng nhận theo nguồn cấp",
      f: "Phân loại theo trường Nguồn cấp của loại.",
      type: "pie",
      labels: [
        "Cơ quan nhà nước",
        "Tổ chức chứng nhận",
        "Doanh nghiệp tự công bố",
        "Chưa phân loại",
      ],
      ds: [["Loại", [6, 9, 4, 7]]],
    },
    {
      id: "lcc4",
      for: ["H4"],
      t: "Giấy tờ, chứng nhận và tỉ lệ hết hiệu lực, thu hồi theo loại",
      f: "Cột: tổng giấy tờ, chứng nhận của loại. Đường: Giấy tờ, chứng nhận đã hết hiệu lực hoặc thu hồi / Tổng giấy tờ, chứng nhận của loại.",
      type: "combo",
      y2pct: 1,
      y2free: 1,
      labels: [
        "VietGAP",
        "Đủ ĐK ATTP",
        "GlobalGAP",
        "FSSC 22000",
        "Công bố SP",
      ],
      ds: [
        ["Giấy tờ, chứng nhận", [58, 142, 96, 214, 188]],
        ["Tỉ lệ hết hiệu lực, thu hồi (%)", [14, 9, 7, 4, 2], "line"],
      ],
    },
    {
      id: "lcc5",
      for: ["H6"],
      t: "Giấy tờ, chứng nhận phát sinh theo tháng, 3 loại nhiều nhất",
      f: "Đếm theo ngày cấp.",
      type: "line",
      labels: ["T4", "T5", "T6", "T7", "T8", "T9"],
      ds: [
        ["FSSC 22000", [14, 16, 19, 17, 21, 24]],
        ["Công bố SP", [11, 13, 15, 16, 18, 20]],
        ["Giấy chứng nhận ATTP", [8, 9, 12, 10, 13, 15]],
      ],
    },
  ],
  warns: [
    {
      for: ["H2", "H8"],
      t: "Loại giấy tờ, chứng nhận chưa từng được sử dụng",
      sev: "medium",
      n: 14,
      cols: ["Tên loại", "Mã", "Ngày tạo"],
      rows: [
        ["Horse", "20327897-942e-…", "23/03/2026"],
        ["NovaSeele", "6fdafe21-75ea-…", "23/03/2026"],
        ["test", "6c058fc6-8a15-…", "23/03/2026"],
      ],
    },
    {
      for: ["H1", "H3"],
      t: "Loại giấy tờ, chứng nhận thiếu thông tin danh mục",
      sev: "high",
      n: 22,
      cols: ["Tên loại", "Thiếu"],
      rows: [
        ["Chứng nhận FSSC 22000", "Mã nghiệp vụ, thời hạn chuẩn"],
        ["CERT-2909-001", "Tên nghiệp vụ, cơ quan quản lý"],
        ["Sở hữu trí tuệ", "Cơ quan quản lý, nguồn cấp"],
      ],
    },
    {
      for: ["H7"],
      t: "Loại giấy tờ, chứng nhận nghi trùng lặp",
      sev: "medium",
      n: 3,
      cols: ["Loại A", "Loại B", "Lý do"],
      rows: [
        ["Giấy chứng nhận ATTP", "Đủ điều kiện ATTP", "Cùng căn cứ pháp lý"],
        ["test", "test", "Trùng tên"],
      ],
    },
  ],
};
