import type { Mod } from "../types";

/** Danh mục hệ thống › Quy trình tiêu chuẩn TXNG (/danh-muc/mau-su-kien-trong-yeu) */
export const mauSuKienTrongYeu: Mod = {
  k: "cte",
  g: "Danh mục hệ thống",
  t: "Quy trình tiêu chuẩn TXNG",
  d: "Chất lượng thư viện quy trình và mức độ tuân thủ theo quy trình",
  href: "/danh-muc/mau-su-kien-trong-yeu",
  cards: [
    {
      id: "H1",
      l: "Tỉ lệ nhóm hàng bắt buộc có quy trình",
      v: 14,
      t: 7.7,
      k: "core",
      d: 22,
      goal: 85,
    },
    {
      id: "H2",
      l: "Tỉ lệ quy trình đạt chuẩn tối thiểu",
      v: 39,
      t: 8.3,
      k: "core",
      d: 64,
      f: "Quy trình có ≥ 3 công đoạn / Tổng quy trình.",
      goal: 80,
    },
    {
      id: "H3",
      l: "Tỉ lệ UID đạt đủ công đoạn",
      v: 80650,
      t: 3.2,
      k: "core",
      d: 112950,
      goal: 85,
    },
    {
      id: "H4",
      l: "Tỉ lệ quy trình được áp dụng",
      v: 51,
      t: 1.6,
      k: "core",
      d: 64,
      f: "Quy trình có ≥ 1 sản phẩm gán / Tổng quy trình.",
      goal: 80,
    },
    { id: "H5", l: "Tổng số quy trình", v: 64, t: 6.7, k: "scale", goalN: 80 },
    { id: "H6", l: "Quy trình dự thảo", v: 17, t: 13.3, k: "scale" },
    {
      id: "H7",
      l: "Phiên bản cập nhật trong tháng",
      v: 9,
      t: 28.6,
      k: "scale",
    },
    {
      id: "H8",
      l: "Sản phẩm dùng phiên bản đã thay thế",
      v: 212,
      t: -5.4,
      k: "risk",
      bad: 1,
    },
  ],
  charts: [
    {
      id: "cte1",
      for: ["H1", "H2"],
      t: "Thư viện quy trình đáp ứng tiêu chuẩn",
      f: "Nhóm hàng: nhóm hàng hóa bắt buộc truy xuất đã có quy trình / Tổng nhóm bắt buộc. Quy trình: số quy trình đạt tiêu chí / 64.",
      type: "ratio",
      items: [
        ["Nhóm hàng bắt buộc đã có quy trình", 14, 22],
        ["Quy trình có ≥ 3 công đoạn", 39, 64],
        ["Quy trình đã khai báo đủ KDE bắt buộc", 47, 64],
        ["Quy trình có cơ quan ban hành", 58, 64],
      ],
    },
    {
      id: "cte2",
      for: ["H3"],
      t: "Tỉ lệ UID đạt đủ công đoạn theo quy trình",
      f: "UID đạt đủ công đoạn / UID đã kích hoạt được gán quy trình, 6 quy trình nhiều UID nhất.",
      type: "hbar",
      pct: 1,
      labels: [
        "Sữa tiệt trùng v3",
        "Gạo hữu cơ v2",
        "Rau, quả tươi v1",
        "Tôm hữu cơ v1",
        "Thịt gia súc v2",
        "Cá v4",
      ],
      ds: [["Đạt", [94, 86, 74, 62, 54, 48]]],
    },
    {
      id: "cte3",
      for: ["H2", "H3"],
      t: "Số công đoạn trong quy trình và tỉ lệ đạt",
      f: "Cột: số quy trình theo số sự kiện trọng yếu của phiên bản đang áp dụng. Đường: tỉ lệ UID đạt đủ công đoạn trung bình của nhóm quy trình đó.",
      type: "combo",
      y2pct: 1,
      labels: ["1", "2", "3", "4", "5", "≥ 6"],
      ds: [
        ["Số quy trình", [14, 11, 15, 12, 8, 4]],
        ["Tỉ lệ đạt (%)", [91, 84, 76, 70, 66, 61], "line"],
      ],
    },
    {
      id: "cte4",
      for: ["H4", "H5"],
      t: "Quy trình theo cơ quan ban hành",
      f: "Đếm quy trình đang áp dụng theo cơ quan ban hành.",
      type: "pie",
      labels: [
        "Bộ NN&MT",
        "Bộ Y tế",
        "Bộ Công Thương",
        "Bộ KH&CN",
        "Chưa có cơ quan",
      ],
      ds: [["Quy trình", [26, 14, 12, 6, 6]]],
    },
    {
      id: "cte5",
      for: ["H3"],
      t: "Công đoạn bắt buộc hay bị thiếu",
      f: "Số UID thiếu theo từng công đoạn bắt buộc (một UID có thể thiếu nhiều công đoạn).",
      type: "hbar",
      labels: [
        "Xuất hàng",
        "Tiếp nhận",
        "Kiểm tra chất lượng",
        "Sản xuất, chế biến",
        "Đóng gói",
      ],
      ds: [["UID thiếu", [11400, 9800, 8200, 5600, 2900]]],
    },
    {
      id: "cte6",
      for: ["H3"],
      t: "Tỉ lệ UID đạt của các quy trình chính theo tháng",
      f: "UID đạt đủ công đoạn / UID đã kích hoạt của quy trình, tại cuối mỗi tháng.",
      type: "line",
      pct: 1,
      labels: ["T4", "T5", "T6", "T7", "T8", "T9"],
      ds: [
        ["Rau, quả tươi v1", [64, 66, 68, 70, 72, 74]],
        ["Cá v4", [39, 41, 43, 45, 46, 48]],
        ["Gạo hữu cơ v2", [79, 80, 82, 83, 85, 86]],
      ],
    },
    {
      id: "cteB",
      t: "Nhóm hàng bắt buộc có quy trình theo bộ",
      f: "Nhóm hàng bắt buộc thuộc phạm vi bộ đã có quy trình / Nhóm hàng bắt buộc thuộc phạm vi bộ.",
      type: "hbar",
      for: ["H1"],
      pct: 1,
      labels: ["Bộ NN&MT", "Bộ Y tế", "Bộ Công Thương"],
      ds: [["Đã có quy trình", [89, 57, 33]]],
    },
    {
      id: "cteP",
      t: "Quy trình ban hành và phiên bản cập nhật theo tháng",
      f: "Ban hành: quy trình mới chuyển Đang áp dụng. Cập nhật: phiên bản mới của quy trình đã có. Dự thảo: tồn tại cuối tháng.",
      type: "line",
      for: ["H5", "H6", "H7"],
      labels: ["T4", "T5", "T6", "T7", "T8", "T9"],
      ds: [
        ["Ban hành mới", [6, 7, 5, 8, 6, 4]],
        ["Phiên bản cập nhật", [3, 5, 4, 6, 7, 9]],
        ["Dự thảo", [11, 12, 14, 13, 15, 17]],
      ],
    },
    {
      id: "cteV",
      t: "Sản phẩm dùng phiên bản đã thay thế theo quy trình",
      f: "Sản phẩm đang gán phiên bản cũ của quy trình đã có phiên bản mới.",
      type: "hbar",
      for: ["H8"],
      labels: ["CTE-FISH", "CTE-ORG-RICE", "Thịt gia súc", "Rau, quả tươi"],
      ds: [["Sản phẩm", [96, 58, 37, 21]]],
    },
  ],
  warns: [
    {
      for: ["H2"],
      t: "Quy trình dưới chuẩn tối thiểu (dưới 3 công đoạn)",
      sev: "high",
      n: 25,
      cols: ["Mã quy trình", "Tên quy trình", "Số công đoạn", "Sản phẩm gán"],
      rows: [
        [
          "CTE-2909-001",
          "Quy trình TXNG rau, quả, cây lương thực tươi",
          1,
          642,
        ],
        ["CTE-ORG-RICE", "Quy trình TXNG gạo hữu cơ", 1, 188],
        ["CTE-FISH", "Quy trình TXNG cá", 2, 310],
        ["CTE-1509-001", "CTE-1509-001", 1, 0],
      ],
    },
    {
      for: ["H3"],
      t: "Quy trình có tỉ lệ đạt dưới 50%",
      sev: "critical",
      n: 4,
      cols: ["Quy trình", "UID áp dụng", "Tỉ lệ đạt", "Công đoạn hay thiếu"],
      rows: [
        ["Cá v4", 21500, "48%", "Kiểm tra chất lượng"],
        ["Thủy sản xuất khẩu v1", 8800, "44%", "Xuất hàng"],
        ["Dược liệu GACP v1", 2900, "39%", "Thu hái"],
      ],
    },
    {
      for: ["H8", "H4"],
      t: "Sản phẩm đang dùng phiên bản quy trình đã thay thế",
      sev: "medium",
      n: 212,
      cols: ["Sản phẩm", "Đang dùng", "Phiên bản mới"],
      rows: [
        ["Cá basa phi lê", "CTE-FISH v3", "v4"],
        ["Gạo ST25 túi 5kg", "CTE-ORG-RICE v1", "v2"],
        ["Nước mắm Cửu Long", "CTE-FISH v2", "v4"],
      ],
    },
  ],
};
