import type { Mod } from "../types";

/** Danh mục hệ thống › Mức độ rủi ro (/danh-muc/muc-do-rui-ro) */
export const mucDoRuiRo: Mod = {
  k: "mdrr",
  g: "Danh mục hệ thống",
  t: "Mức độ rủi ro",
  d: "Danh mục mức độ rủi ro an toàn thực phẩm dùng để phân loại cơ sở, sản phẩm và tần suất kiểm tra",
  href: "/danh-muc/muc-do-rui-ro",
  cards: [
    {
      id: "H1",
      l: "Tỉ lệ cơ sở đã xếp mức rủi ro",
      v: 902,
      t: 4.1,
      k: "core",
      d: 1064,
      f: "Cơ sở có mức rủi ro / Tổng cơ sở.",
    },
    {
      id: "H2",
      l: "Tỉ lệ cơ sở rủi ro cao được kiểm tra đúng tần suất",
      v: 118,
      t: 3.5,
      k: "core",
      d: 146,
      f: "Cơ sở rủi ro cao được kiểm tra ≥ 2 lần/năm / Cơ sở rủi ro cao.",
    },
    {
      id: "H3",
      l: "Tỉ lệ xếp hạng cập nhật trong 12 tháng",
      v: 781,
      t: 2,
      k: "core",
      d: 902,
      f: "Cơ sở được đánh giá lại mức rủi ro trong 12 tháng / Cơ sở đã xếp mức.",
    },
    {
      id: "H4",
      l: "Tỉ lệ mức rủi ro có tiêu chí định lượng",
      v: 4,
      t: 0,
      k: "core",
      d: 4,
      f: "Mức rủi ro có bộ tiêu chí chấm điểm / Tổng mức.",
    },
    { id: "H5", l: "Số mức rủi ro", v: 4, t: 0, k: "scale" },
    {
      id: "H6",
      l: "Cơ sở được xếp lại trong tháng",
      v: 64,
      t: 14.3,
      k: "scale",
    },
    { id: "H7", l: "Cơ sở tăng mức rủi ro", v: 17, t: 21.4, k: "risk", bad: 1 },
    {
      id: "H8",
      l: "Cơ sở chưa xếp mức rủi ro",
      v: 162,
      t: -8.5,
      k: "risk",
      bad: 1,
    },
  ],
  charts: [
    {
      id: "mdrr1",
      for: ["H1", "H5"],
      t: "Phân bố cơ sở theo mức rủi ro",
      f: "Đếm cơ sở theo mức rủi ro hiện tại.",
      type: "pie",
      labels: ["Thấp", "Trung bình", "Cao", "Rất cao", "Chưa xếp"],
      ds: [["Cơ sở", [412, 344, 118, 28, 162]]],
    },
    {
      id: "mdrr2",
      for: ["H2"],
      t: "Tỉ lệ kiểm tra đúng tần suất theo mức",
      f: "Cơ sở được kiểm tra đúng tần suất quy định / Cơ sở của mức.",
      type: "bar",
      pct: 1,
      labels: ["Thấp", "Trung bình", "Cao", "Rất cao"],
      ds: [["Đúng tần suất", [92, 86, 81, 75]]],
    },
    {
      id: "mdrr3",
      for: ["H6", "H7"],
      t: "Thay đổi mức rủi ro theo tháng",
      f: "Số cơ sở được xếp lại; tách tăng và giảm mức.",
      type: "stack",
      labels: ["T4", "T5", "T6", "T7", "T8", "T9"],
      ds: [
        ["Giảm mức", [21, 24, 28, 31, 36, 47]],
        ["Tăng mức", [9, 11, 8, 12, 14, 17]],
      ],
    },
  ],
  warns: [
    {
      t: "Cơ sở rủi ro rất cao chưa được kiểm tra trong 6 tháng",
      sev: "critical",
      n: 5,
      cols: ["Cơ sở", "Loại hình", "Tỉnh/thành", "Kiểm tra gần nhất"],
      rows: [
        ["Bếp ăn KCN Quang Minh", "Bếp ăn tập thể", "Hà Nội", "12/02/2026"],
        ["Cơ sở giết mổ Bình Chánh", "Giết mổ", "TP.HCM", "04/03/2026"],
      ],
      for: ["H2"],
    },
    {
      t: "Cơ sở tăng mức rủi ro trong tháng",
      sev: "high",
      n: 17,
      cols: ["Cơ sở", "Mức cũ", "Mức mới", "Lý do"],
      rows: [
        ["Nhà hàng Hải Đăng", "Trung bình", "Cao", "Vi phạm khi kiểm tra"],
        [
          "Cty TNHH Suất ăn Minh Phát",
          "Cao",
          "Rất cao",
          "Liên quan vụ ngộ độc",
        ],
      ],
      for: ["H6", "H7"],
    },
  ],
};
