import type { Mod } from "../types";

/** Quản lý ATTP › Ngộ độc thực phẩm (/ngo-doc/danh-sach) */
export const ngoDocThucPham: Mod = {
  k: "nd",
  g: "Quản lý ATTP",
  t: "Ngộ độc thực phẩm",
  d: "Giám sát, điều tra và xử lý các vụ ngộ độc thực phẩm",
  href: "/ngo-doc/danh-sach",
  cards: [
    {
      id: "H1",
      l: "Tỉ lệ vụ xác định được nguyên nhân",
      v: 11,
      t: 8.3,
      k: "core",
      d: 14,
      f: "Vụ đã có kết luận nguyên nhân / Tổng vụ ngộ độc trong kỳ.",
    },
    {
      id: "H2",
      l: "Tỉ lệ vụ truy xuất được nguồn thực phẩm",
      v: 9,
      t: 12.5,
      k: "core",
      d: 14,
      f: "Vụ xác định được lô, cơ sở cung cấp thực phẩm nghi ngờ / Tổng vụ.",
    },
    {
      id: "H3",
      l: "Tỉ lệ vụ báo cáo trong 24 giờ",
      v: 12,
      t: 5,
      k: "core",
      d: 14,
      f: "Vụ được báo cáo lên hệ thống trong 24 giờ kể từ khi phát hiện / Tổng vụ.",
    },
    {
      id: "H4",
      l: "Tỉ lệ người mắc đã xuất viện",
      v: 318,
      t: 2.2,
      k: "core",
      d: 327,
      f: "Người mắc đã xuất viện / Tổng người mắc.",
    },
    { id: "H5", l: "Số vụ ngộ độc", v: 14, t: -17.6, k: "scale", bad: 1 },
    { id: "H6", l: "Số người mắc", v: 327, t: -9.4, k: "scale", bad: 1 },
    { id: "H7", l: "Số người tử vong", v: 1, t: 0, k: "risk", bad: 1 },
    { id: "H8", l: "Vụ trên 30 người mắc", v: 3, t: -25, k: "risk", bad: 1 },
  ],
  charts: [
    {
      id: "nd1",
      for: ["H5", "H6"],
      t: "Vụ ngộ độc và người mắc theo tháng",
      f: "Cột: số vụ ngộ độc. Đường: số người mắc.",
      type: "combo",
      labels: ["T4", "T5", "T6", "T7", "T8", "T9"],
      ds: [
        ["Số vụ", [11, 15, 19, 17, 17, 14]],
        ["Người mắc", [214, 388, 462, 401, 361, 327], "line"],
      ],
    },
    {
      id: "nd2",
      for: ["H1"],
      t: "Nguyên nhân ngộ độc",
      f: "Đếm vụ đã có kết luận theo nhóm nguyên nhân.",
      type: "pie",
      labels: [
        "Vi sinh vật",
        "Hóa chất, phụ gia",
        "Độc tố tự nhiên",
        "Thực phẩm biến chất",
        "Chưa xác định",
      ],
      ds: [["Vụ", [5, 2, 2, 2, 3]]],
    },
    {
      id: "nd3",
      for: ["H5"],
      t: "Bữa ăn, địa điểm xảy ra ngộ độc",
      f: "Đếm vụ theo loại hình bữa ăn trong kỳ.",
      type: "hbar",
      labels: [
        "Bếp ăn tập thể",
        "Đám cưới, đám giỗ",
        "Thức ăn đường phố",
        "Gia đình",
        "Nhà hàng",
      ],
      ds: [["Vụ", [5, 4, 2, 2, 1]]],
    },
    {
      id: "nd4",
      for: ["H2", "H3"],
      t: "Năng lực phản ứng",
      f: "Số vụ đạt từng tiêu chí / Tổng vụ (14).",
      type: "ratio",
      items: [
        ["Báo cáo trong 24 giờ", 12, 14],
        ["Lấy được mẫu thực phẩm lưu", 10, 14],
        ["Truy xuất được nguồn thực phẩm", 9, 14],
        ["Có kết luận nguyên nhân", 11, 14],
      ],
    },
  ],
  warns: [
    {
      t: "Vụ ngộ độc chưa có kết luận nguyên nhân quá 15 ngày",
      sev: "critical",
      n: 3,
      cols: ["Vụ việc", "Địa điểm", "Số người mắc", "Ngày xảy ra"],
      rows: [
        ["Ngộ độc bếp ăn KCN Quang Minh", "Hà Nội", 86, "02/09/2026"],
        ["Ngộ độc tiệc cưới", "Long An", 41, "08/09/2026"],
        ["Ngộ độc bánh mì", "TP.HCM", 23, "14/09/2026"],
      ],
      for: ["H1"],
    },
    {
      t: "Cơ sở cung cấp thực phẩm liên quan vụ ngộ độc chưa bị đình chỉ, kiểm tra",
      sev: "high",
      n: 2,
      cols: ["Cơ sở", "Vụ liên quan", "Loại hình", "Trạng thái"],
      rows: [
        [
          "Cty TNHH Suất ăn Minh Phát",
          "KCN Quang Minh",
          "Bếp ăn tập thể",
          "Đang hoạt động",
        ],
        [
          "Lò bánh mì Hòa Hưng",
          "Ngộ độc bánh mì",
          "Kinh doanh",
          "Đang hoạt động",
        ],
      ],
      for: ["H2"],
    },
  ],
};
