import type { Mod } from "../types";

/** Quản trị hệ thống › Người dùng (/quan-tri/nguoi-dung) */
export const nguoiDung: Mod = {
  k: "nguoidung",
  g: "Quản trị hệ thống",
  t: "Người dùng",
  d: "Tài khoản cán bộ quản lý, doanh nghiệp và đơn vị cung cấp giải pháp",
  href: "/quan-tri/nguoi-dung",
  cards: [
    {
      id: "H1",
      l: "Tỉ lệ tài khoản hoạt động 30 ngày",
      v: 1218,
      t: 3.6,
      k: "core",
      d: 1694,
      f: "Tài khoản đăng nhập trong 30 ngày / Tài khoản đang kích hoạt.",
    },
    {
      id: "H2",
      l: "Tỉ lệ tài khoản bật xác thực 2 lớp",
      v: 982,
      t: 8.8,
      k: "core",
      d: 1694,
      f: "Tài khoản bật xác thực 2 lớp / Tài khoản đang kích hoạt.",
    },
    {
      id: "H3",
      l: "Tỉ lệ tài khoản đã gán vai trò",
      v: 1651,
      t: 0.6,
      k: "core",
      d: 1694,
      f: "Tài khoản có ≥ 1 vai trò / Tài khoản đang kích hoạt.",
    },
    {
      id: "H4",
      l: "Tỉ lệ tài khoản định danh VNeID",
      v: 744,
      t: 12.4,
      k: "core",
      d: 1694,
      f: "Tài khoản liên kết định danh điện tử VNeID / Tài khoản đang kích hoạt.",
    },
    { id: "H5", l: "Tài khoản đang kích hoạt", v: 1694, t: 4.9, k: "scale" },
    { id: "H6", l: "Tài khoản mới trong tháng", v: 121, t: 6.1, k: "scale" },
    {
      id: "H7",
      l: "Tài khoản không đăng nhập quá 90 ngày",
      v: 214,
      t: -3.2,
      k: "risk",
      bad: 1,
    },
    {
      id: "H8",
      l: "Đăng nhập thất bại bất thường",
      v: 37,
      t: 15.6,
      k: "risk",
      bad: 1,
    },
  ],
  charts: [
    {
      id: "nd_u1",
      for: ["H5"],
      t: "Cơ cấu tài khoản theo loại",
      f: "Đếm tài khoản đang kích hoạt theo loại đơn vị.",
      type: "pie",
      labels: [
        "Doanh nghiệp",
        "Cán bộ cơ quan quản lý",
        "Đơn vị cung cấp giải pháp",
        "Quản trị hệ thống",
      ],
      ds: [["Tài khoản", [1182, 384, 112, 16]]],
    },
    {
      id: "nd_u2",
      for: ["H1"],
      t: "Người dùng hoạt động theo tháng",
      f: "Tài khoản có đăng nhập trong 30 ngày tính đến cuối tháng.",
      type: "line",
      labels: ["T4", "T5", "T6", "T7", "T8", "T9"],
      ds: [["Hoạt động", [902, 968, 1031, 1102, 1164, 1218]]],
    },
    {
      id: "nd_u3",
      for: ["H2", "H3", "H4"],
      t: "Mức độ an toàn tài khoản",
      f: "Tài khoản đạt tiêu chí / Tài khoản đang kích hoạt (1.694).",
      type: "ratio",
      items: [
        ["Đã gán vai trò", 1651, 1694],
        ["Bật xác thực 2 lớp", 982, 1694],
        ["Liên kết VNeID", 744, 1694],
        ["Đổi mật khẩu trong 90 ngày", 1103, 1694],
      ],
    },
  ],
  warns: [
    {
      t: "Tài khoản quản trị không bật xác thực 2 lớp",
      sev: "critical",
      n: 3,
      cols: ["Tài khoản", "Vai trò", "Đơn vị", "Đăng nhập cuối"],
      rows: [
        ["admin.hn", "Quản trị hệ thống", "Sở KH&CN Hà Nội", "29/09/2026"],
        ["qt.bonnmt", "Quản trị đơn vị", "Bộ NN&MT", "27/09/2026"],
      ],
      for: ["H2"],
    },
    {
      t: "Tài khoản không đăng nhập quá 90 ngày chưa bị khóa",
      sev: "medium",
      n: 214,
      cols: ["Tài khoản", "Loại", "Đơn vị", "Đăng nhập cuối"],
      rows: [
        [
          "dn.vietxanh",
          "Doanh nghiệp",
          "Cty TNHH Nông sản Việt Xanh",
          "12/05/2026",
        ],
        ["cb.longan02", "Cán bộ", "Sở Y tế Long An", "03/06/2026"],
      ],
      for: ["H1", "H7"],
    },
  ],
};
