import type { Mod } from "../types";

/** Tích hợp hệ thống › Nhật ký giao dịch (/tich-hop/transaction) */
export const nhatKyGiaoDich: Mod = {
  k: "gd",
  g: "Tích hợp hệ thống",
  t: "Nhật ký giao dịch",
  d: "Nhật ký ghi nhận giao dịch, chứng chỉ số lên sổ cái blockchain",
  href: "/tich-hop/transaction",
  cards: [
    {
      id: "H1",
      l: "Tỉ lệ giao dịch ghi sổ cái thành công",
      v: 479120,
      t: 0.4,
      k: "core",
      d: 482310,
      f: "Giao dịch xác nhận trên sổ cái blockchain / Giao dịch gửi.",
    },
    {
      id: "H2",
      l: "Tỉ lệ giao dịch xác nhận dưới 30 giây",
      v: 463800,
      t: 1.6,
      k: "core",
      d: 479120,
      f: "Giao dịch xác nhận trong 30 giây / Giao dịch thành công.",
    },
    {
      id: "H3",
      l: "Tỉ lệ đối soát khớp với cơ sở dữ liệu",
      v: 99.97,
      t: 0.01,
      k: "core",
      d: 100,
      f: "Bản ghi khớp hash giữa sổ cái và cơ sở dữ liệu / Bản ghi đối soát (%).",
    },
    {
      id: "H4",
      l: "Tỉ lệ thời gian hoạt động của nút",
      v: 99.92,
      t: 0.05,
      k: "core",
      d: 100,
      f: "Thời gian các nút sổ cái hoạt động / Tổng thời gian (%).",
    },
    { id: "H5", l: "Giao dịch trong tháng", v: 482310, t: 12.1, k: "scale" },
    { id: "H6", l: "Số nút đang hoạt động", v: 7, t: 0, k: "scale" },
    {
      id: "H7",
      l: "Giao dịch đang chờ xác nhận",
      v: 214,
      t: -18.3,
      k: "risk",
      bad: 1,
    },
    {
      id: "H8",
      l: "Bản ghi lệch khi đối soát",
      v: 3,
      t: -50,
      k: "risk",
      bad: 1,
    },
  ],
  charts: [
    {
      id: "gd1",
      for: ["H5"],
      t: "Giao dịch theo loại",
      f: "Đếm giao dịch trong tháng theo loại.",
      type: "pie",
      labels: [
        "Chứng chỉ số sự kiện",
        "Kích hoạt UID",
        "Cập nhật sản phẩm",
        "Giấy tờ, chứng nhận",
      ],
      ds: [["Giao dịch", [302140, 148220, 21480, 10470]]],
    },
    {
      id: "gd2",
      for: ["H2"],
      t: "Thời gian xác nhận trung bình theo tháng",
      f: "Trung bình số giây từ khi gửi đến khi xác nhận trên sổ cái.",
      type: "line",
      labels: ["T4", "T5", "T6", "T7", "T8", "T9"],
      ds: [["Giây", [14.2, 12.8, 11.9, 10.4, 9.8, 9.1]]],
    },
  ],
  warns: [
    {
      t: "Bản ghi lệch hash giữa sổ cái và cơ sở dữ liệu",
      sev: "critical",
      n: 3,
      cols: ["Mã giao dịch", "Loại", "Thời điểm", "Trạng thái"],
      rows: [
        [
          "0x8fa2…c91e",
          "Chứng chỉ số sự kiện",
          "28/09/2026 10:21",
          "Đang điều tra",
        ],
        ["0x1b07…4ad3", "Kích hoạt UID", "29/09/2026 15:02", "Đang điều tra"],
      ],
      for: ["H3", "H8"],
    },
    {
      t: "Giao dịch chờ xác nhận quá 10 phút",
      sev: "high",
      n: 214,
      cols: ["Mã giao dịch", "Đơn vị gửi", "Gửi lúc", "Số lần thử"],
      rows: [
        ["0x44c1…09bf", "TrangNTT", "30/09/2026 09:12", 3],
        ["0xa3e0…77d1", "Checkee", "30/09/2026 09:40", 2],
      ],
      for: ["H2", "H7"],
    },
  ],
};
