import type { Mod } from "../types";

/** Danh mục hệ thống › Nhóm sản phẩm (/danh-muc/nhom-san-pham) */
export const nhomSanPham: Mod = {
  k: "nsp",
  g: "Danh mục hệ thống",
  t: "Nhóm sản phẩm",
  d: "Danh mục nhóm sản phẩm dùng cho khai báo sản phẩm và thống kê",
  href: "/danh-muc/nhom-san-pham",
  cards: [
    {
      id: "H1",
      l: "Tỉ lệ sản phẩm đã gán nhóm",
      v: 1634,
      t: 2,
      k: "core",
      d: 1720,
      f: "Sản phẩm có nhóm sản phẩm / Tổng sản phẩm.",
    },
    {
      id: "H2",
      l: "Tỉ lệ nhóm đang có sản phẩm",
      v: 58,
      t: 3.6,
      k: "core",
      d: 64,
      f: "Nhóm có ≥ 1 sản phẩm / Tổng nhóm.",
    },
    {
      id: "H3",
      l: "Tỉ lệ nhóm có bộ trường dữ liệu chủ",
      v: 51,
      t: 6.3,
      k: "core",
      d: 64,
      f: "Nhóm có quy định trường dữ liệu chủ bắt buộc / Tổng nhóm.",
    },
    {
      id: "H4",
      l: "Tỉ lệ nhóm ánh xạ GPC",
      v: 61,
      t: 0,
      k: "core",
      d: 64,
      f: "Nhóm ánh xạ phân loại GS1 GPC / Tổng nhóm.",
    },
    { id: "H5", l: "Tổng số nhóm sản phẩm", v: 64, t: 3.2, k: "scale" },
    { id: "H6", l: "Nhóm thêm mới trong tháng", v: 2, t: 0, k: "scale" },
    {
      id: "H7",
      l: "Nhóm không có sản phẩm",
      v: 6,
      t: -14.3,
      k: "risk",
      bad: 1,
    },
    {
      id: "H8",
      l: 'Sản phẩm xếp nhóm "Khác"',
      v: 74,
      t: 5.7,
      k: "risk",
      bad: 1,
    },
  ],
  charts: [
    {
      id: "nsp1",
      for: ["H1"],
      t: "10 nhóm sản phẩm nhiều sản phẩm nhất",
      f: "Đếm sản phẩm theo nhóm.",
      type: "hbar",
      labels: [
        "Gạo, ngũ cốc",
        "Rau củ quả",
        "Cà phê, chè",
        "Thủy sản đông lạnh",
        "Sữa nước",
        "Nước mắm",
        "Bánh kẹo",
        "Mật ong",
      ],
      ds: [["Sản phẩm", [214, 196, 162, 148, 121, 98, 87, 64]]],
    },
    {
      id: "nsp2",
      for: ["H2", "H3", "H4"],
      t: "Mức độ hoàn thiện danh mục nhóm sản phẩm",
      f: "Nhóm đạt tiêu chí / Tổng nhóm (64).",
      type: "ratio",
      items: [
        ["Đang có sản phẩm", 58, 64],
        ["Có bộ trường dữ liệu chủ", 51, 64],
        ["Ánh xạ GPC", 61, 64],
      ],
    },
  ],
  warns: [
    {
      t: 'Sản phẩm bị xếp vào nhóm "Khác" cần phân loại lại',
      sev: "medium",
      n: 74,
      cols: ["Sản phẩm", "Doanh nghiệp", "GTIN", "Nhóm đề xuất"],
      rows: [
        [
          "Tổ yến chưng",
          "Cty CP Yến Việt",
          "8936011122334",
          "Thực phẩm chế biến",
        ],
        ["Muối tôm Tây Ninh", "HTX Gia vị Tây Ninh", "8936055566677", "Gia vị"],
      ],
      for: ["H1", "H8"],
    },
  ],
};
