import type { Mod } from "../types";

/** Danh mục hệ thống › Nhóm ngành hàng (/danh-muc/nhom-nganh-hang) */
export const nhomNganhHang: Mod = {
  k: "nnh",
  g: "Danh mục hệ thống",
  t: "Nhóm ngành hàng",
  d: "Danh mục nhóm ngành hàng dùng để phân loại sản phẩm, doanh nghiệp và phạm vi quản lý",
  href: "/danh-muc/nhom-nganh-hang",
  cards: [
    {
      id: "H1",
      l: "Tỉ lệ sản phẩm đã gán nhóm ngành hàng",
      v: 1608,
      t: 2.3,
      k: "core",
      d: 1720,
      f: "Sản phẩm có nhóm ngành hàng / Tổng sản phẩm.",
    },
    {
      id: "H2",
      l: "Tỉ lệ nhóm có cơ quan quản lý phụ trách",
      v: 38,
      t: 5.6,
      k: "core",
      d: 42,
      f: "Nhóm ngành hàng gán Bộ, ngành quản lý / Tổng nhóm.",
    },
    {
      id: "H3",
      l: "Tỉ lệ nhóm có quy trình tiêu chuẩn TXNG",
      v: 29,
      t: 7.4,
      k: "core",
      d: 42,
      f: "Nhóm có ≥ 1 quy trình tiêu chuẩn TXNG đang áp dụng / Tổng nhóm.",
    },
    {
      id: "H4",
      l: "Tỉ lệ nhóm ánh xạ phân loại GPC",
      v: 40,
      t: 0,
      k: "core",
      d: 42,
      f: "Nhóm ánh xạ sang mã phân loại sản phẩm toàn cầu GS1 GPC / Tổng nhóm.",
    },
    { id: "H5", l: "Tổng số nhóm ngành hàng", v: 42, t: 2.4, k: "scale" },
    { id: "H6", l: "Nhóm cấp 1", v: 9, t: 0, k: "scale" },
    {
      id: "H7",
      l: "Nhóm chưa có quy trình TXNG",
      v: 13,
      t: -7.1,
      k: "risk",
      bad: 1,
    },
    {
      id: "H8",
      l: "Sản phẩm chưa phân nhóm",
      v: 112,
      t: -9.7,
      k: "risk",
      bad: 1,
    },
  ],
  charts: [
    {
      id: "nnh1",
      for: ["H1", "H5"],
      t: "Sản phẩm theo nhóm ngành hàng cấp 1",
      f: "Đếm sản phẩm theo nhóm cấp 1.",
      type: "hbar",
      labels: [
        "Thực phẩm chế biến",
        "Nông sản tươi",
        "Thủy sản",
        "Sữa & chế phẩm",
        "Đồ uống",
        "Dược liệu",
      ],
      ds: [["Sản phẩm", [512, 398, 264, 188, 146, 100]]],
    },
    {
      id: "nnh2",
      for: ["H2", "H3", "H4"],
      t: "Mức độ hoàn thiện danh mục",
      f: "Nhóm đạt tiêu chí / Tổng nhóm (42).",
      type: "ratio",
      items: [
        ["Có cơ quan quản lý", 38, 42],
        ["Có quy trình tiêu chuẩn TXNG", 29, 42],
        ["Ánh xạ GPC", 40, 42],
      ],
    },
  ],
  warns: [
    {
      t: "Nhóm ngành hàng có sản phẩm nhưng chưa có quy trình tiêu chuẩn TXNG",
      sev: "high",
      n: 13,
      cols: ["Nhóm", "Sản phẩm", "Cơ quan quản lý", "Doanh nghiệp"],
      rows: [
        ["Gia vị", "64", "Bộ Công Thương", 22],
        ["Bánh kẹo", "58", "Bộ Công Thương", 19],
      ],
      for: ["H3", "H7"],
    },
  ],
};
