import type { Mod } from "../types";

/** Truy xuất nguồn gốc › Phản ánh sản phẩm (/quan-tri/bao-cao-san-pham) */
export const phanAnhSanPham: Mod = {
  k: "pa",
  g: "Truy xuất nguồn gốc",
  t: "Phản ánh sản phẩm",
  d: "Phản ánh của người tiêu dùng về sản phẩm qua kênh quét UID",
  href: "/quan-tri/bao-cao-san-pham",
  cards: [
    {
      id: "H1",
      l: "Tỉ lệ phản ánh được xử lý trong hạn",
      v: 184,
      t: 5.4,
      k: "core",
      d: 226,
      f: "Phản ánh đóng trong 7 ngày làm việc / Phản ánh đã tiếp nhận.",
    },
    {
      id: "H2",
      l: "Tỉ lệ phản ánh được doanh nghiệp phản hồi",
      v: 197,
      t: 3.2,
      k: "core",
      d: 226,
      f: "Phản ánh có phản hồi của doanh nghiệp / Phản ánh đã chuyển doanh nghiệp.",
    },
    {
      id: "H3",
      l: "Tỉ lệ phản ánh xác minh đúng",
      v: 71,
      t: -2.1,
      k: "core",
      d: 198,
      f: "Phản ánh xác minh có vi phạm / Phản ánh đã xác minh.",
    },
    {
      id: "H4",
      l: "Tỉ lệ người phản ánh hài lòng",
      v: 142,
      t: 4,
      k: "core",
      d: 176,
      f: "Đánh giá hài lòng / Phản ánh có đánh giá sau xử lý.",
    },
    { id: "H5", l: "Phản ánh tiếp nhận", v: 226, t: 14.1, k: "scale" },
    { id: "H6", l: "Phản ánh mới trong tháng", v: 48, t: 9.1, k: "scale" },
    { id: "H7", l: "Phản ánh quá hạn xử lý", v: 42, t: 7.7, k: "risk", bad: 1 },
    {
      id: "H8",
      l: "Phản ánh nghi hàng giả",
      v: 19,
      t: 26.7,
      k: "risk",
      bad: 1,
    },
  ],
  charts: [
    {
      id: "pa1",
      for: ["H5", "H6"],
      t: "Phản ánh theo tháng và theo loại",
      f: "Số phản ánh tiếp nhận trong tháng, tách theo loại.",
      type: "stack",
      labels: ["T4", "T5", "T6", "T7", "T8", "T9"],
      ds: [
        ["Chất lượng sản phẩm", [12, 14, 15, 17, 19, 21]],
        ["Nghi hàng giả", [3, 4, 2, 5, 4, 6]],
        ["Thông tin truy xuất sai", [9, 8, 11, 12, 14, 15]],
        ["Khác", [4, 5, 3, 5, 6, 6]],
      ],
    },
    {
      id: "pa2",
      for: ["H1", "H7"],
      t: "Thời gian xử lý phản ánh",
      f: "Phân bố phản ánh đã đóng theo số ngày xử lý.",
      type: "bar",
      labels: ["≤ 2 ngày", "3–5 ngày", "6–7 ngày", "8–15 ngày", "> 15 ngày"],
      ds: [["Phản ánh", [58, 74, 52, 28, 14]]],
    },
    {
      id: "pa3",
      for: ["H3", "H8"],
      t: "Nhóm sản phẩm bị phản ánh nhiều nhất",
      f: "Số phản ánh theo nhóm sản phẩm.",
      type: "hbar",
      labels: [
        "Thực phẩm chức năng",
        "Sữa & chế phẩm",
        "Đồ uống",
        "Thực phẩm chế biến",
        "Nông sản tươi",
      ],
      ds: [["Phản ánh", [64, 48, 41, 39, 34]]],
    },
    {
      id: "pa4",
      for: ["H4"],
      t: "Mức độ hài lòng sau xử lý",
      f: "Đếm đánh giá của người phản ánh.",
      type: "pie",
      labels: ["Hài lòng", "Bình thường", "Không hài lòng"],
      ds: [["Đánh giá", [142, 21, 13]]],
    },
  ],
  warns: [
    {
      t: "Phản ánh nghi hàng giả chưa chuyển cơ quan chức năng",
      sev: "critical",
      n: 7,
      cols: ["Sản phẩm", "UID", "Địa điểm quét", "Ngày phản ánh"],
      rows: [
        ["Sữa bột trẻ em 900g", "UID-8F21C9", "TP.HCM", "24/09/2026"],
        [
          "Thực phẩm bảo vệ sức khỏe Omega",
          "UID-2B77A0",
          "Hà Nội",
          "21/09/2026",
        ],
      ],
      for: ["H8", "H1"],
    },
    {
      t: "Phản ánh quá hạn chưa có phản hồi doanh nghiệp",
      sev: "high",
      n: 29,
      cols: ["Phản ánh", "Doanh nghiệp", "Ngày chuyển", "Quá hạn (ngày)"],
      rows: [
        ["PA-2609-018", "Cty TP Hà Thành", "10/09/2026", 19],
        ["PA-2609-007", "Cty CP Tech Brand", "04/09/2026", 25],
      ],
      for: ["H2", "H7"],
    },
  ],
};
