import type { Mod } from "../types";

/** Danh mục hệ thống › Phân loại cơ sở (/danh-muc/phan-loai-co-so) */
export const phanLoaiCoSo: Mod = {
  k: "plcs",
  g: "Danh mục hệ thống",
  t: "Phân loại cơ sở",
  d: "Danh mục loại hình cơ sở sản xuất, kinh doanh thực phẩm",
  href: "/danh-muc/phan-loai-co-so",
  cards: [
    {
      id: "H1",
      l: "Tỉ lệ cơ sở đã phân loại",
      v: 915,
      t: 3.4,
      k: "core",
      d: 1064,
      f: "Cơ sở có loại hình / Tổng cơ sở.",
    },
    {
      id: "H2",
      l: "Tỉ lệ loại hình có quy định điều kiện ATTP",
      v: 14,
      t: 0,
      k: "core",
      d: 16,
      f: "Loại hình có liên kết văn bản quy định điều kiện / Tổng loại hình.",
    },
    {
      id: "H3",
      l: "Tỉ lệ loại hình xác định diện cấp chứng nhận",
      v: 16,
      t: 0,
      k: "core",
      d: 16,
      f: "Loại hình đã xác định thuộc/không thuộc diện cấp giấy chứng nhận ATTP / Tổng loại hình.",
    },
    {
      id: "H4",
      l: "Tỉ lệ loại hình đang có cơ sở",
      v: 15,
      t: 7.1,
      k: "core",
      d: 16,
      f: "Loại hình có ≥ 1 cơ sở / Tổng loại hình.",
    },
    { id: "H5", l: "Tổng số loại hình", v: 16, t: 6.7, k: "scale" },
    {
      id: "H6",
      l: "Cơ sở phân loại mới trong tháng",
      v: 71,
      t: 9.2,
      k: "scale",
    },
    { id: "H7", l: "Cơ sở chưa phân loại", v: 149, t: -6.9, k: "risk", bad: 1 },
    {
      id: "H8",
      l: "Cơ sở phân loại sai diện chứng nhận",
      v: 12,
      t: -20,
      k: "risk",
      bad: 1,
    },
  ],
  charts: [
    {
      id: "plcs1",
      for: ["H1", "H5"],
      t: "Cơ sở theo loại hình",
      f: "Đếm cơ sở theo loại hình chính.",
      type: "pie",
      labels: [
        "Sản xuất thực phẩm",
        "Kinh doanh, bán lẻ",
        "Nhà hàng, ăn uống",
        "Kho, trung chuyển",
        "Chưa phân loại",
      ],
      ds: [["Cơ sở", [412, 298, 121, 84, 149]]],
    },
    {
      id: "plcs2",
      for: ["H6", "H7"],
      t: "Cơ sở chưa phân loại theo tháng",
      f: "Số cơ sở chưa có loại hình tại cuối mỗi tháng.",
      type: "line",
      labels: ["T4", "T5", "T6", "T7", "T8", "T9"],
      ds: [["Chưa phân loại", [262, 231, 204, 181, 160, 149]]],
    },
  ],
  warns: [
    {
      t: "Cơ sở thuộc diện cấp chứng nhận nhưng được phân loại miễn",
      sev: "high",
      n: 12,
      cols: ["Cơ sở", "Loại hình hiện tại", "Loại hình đề xuất", "Tỉnh/thành"],
      rows: [
        [
          "Cơ sở bún tươi Phú Đô",
          "Kinh doanh, bán lẻ",
          "Sản xuất thực phẩm",
          "Hà Nội",
        ],
        [
          "Xưởng đá viên Hòa Bình",
          "Kho, trung chuyển",
          "Sản xuất thực phẩm",
          "Đà Nẵng",
        ],
      ],
      for: ["H8"],
    },
  ],
};
