import type { Mod } from "../types";

/** Truy xuất nguồn gốc › Sản phẩm (/truy-xuat/san-pham) */
export const sanPham: Mod = {
  k: "sp",
  g: "Truy xuất nguồn gốc",
  t: "Sản phẩm",
  d: "Dữ liệu chủ sản phẩm, hàng hóa theo mã GTIN do tổ chức, cá nhân khai báo",
  href: "/truy-xuat/san-pham",
  cards: [
    {
      id: "H1",
      l: "Tỉ lệ sản phẩm đủ dữ liệu chủ",
      v: 2986,
      t: 3.6,
      k: "core",
      d: 5154,
      f: "Sản phẩm tổ chức, cá nhân đã khai báo đủ mọi trường bắt buộc (do Bộ quản lý ngành ban hành) / Tổng sản phẩm.",
      goal: 85,
    },
    {
      id: "H2",
      l: "Tỉ lệ GTIN hợp lệ",
      v: 5112,
      t: 0.3,
      k: "core",
      d: 5154,
      f: "GTIN đúng độ dài, đúng số kiểm tra, GCP khớp doanh nghiệp / Tổng sản phẩm.",
      goal: 90,
    },
    {
      id: "H3",
      l: "Tỉ lệ sản phẩm diện công bố có hồ sơ",
      v: 2080,
      t: 4.1,
      k: "core",
      d: 3185,
      f: "Sản phẩm thuộc diện công bố đã có hồ sơ công bố / Sản phẩm thuộc diện công bố.",
      goal: 85,
    },
    {
      id: "H4",
      l: "Tỉ lệ sản phẩm đã cấp UID",
      v: 1886,
      t: 7.4,
      k: "core",
      d: 5154,
      f: "Sản phẩm có ≥ 1 UID / Tổng sản phẩm.",
      goal: 80,
    },
    {
      id: "H5",
      l: "Tổng số sản phẩm",
      v: 5154,
      t: 4.9,
      k: "scale",
      goalN: 6000,
    },
    { id: "H6", l: "Sản phẩm mới trong tháng", v: 262, t: 9.2, k: "scale" },
    {
      id: "H7",
      l: "Tỉ lệ đủ dữ liệu chủ của sản phẩm mới",
      v: 176,
      t: 6,
      k: "core",
      d: 262,
      f: "Sản phẩm khai báo trong tháng đã đủ dữ liệu chủ ngay khi tạo / Sản phẩm khai báo trong tháng. Đo chất lượng đầu vào.",
      goal: 85,
    },
    {
      id: "H8",
      l: "Tỉ lệ sản phẩm đã gán quy trình",
      v: 1530,
      t: 5.5,
      k: "core",
      d: 5154,
      f: "Sản phẩm đã gán phiên bản quy trình tiêu chuẩn TXNG đang áp dụng / Tổng sản phẩm.",
      goal: 80,
    },
  ],
  charts: [
    {
      id: "sp1",
      for: ["H1"],
      t: "Tỉ lệ doanh nghiệp khai báo đủ từng trường dữ liệu chủ",
      f: "Sản phẩm có trường do doanh nghiệp khai báo và hợp lệ / Sản phẩm thuộc diện bắt buộc trường đó. Nền tảng chỉ kiểm tra định dạng, không tự điền thay doanh nghiệp. Hồ sơ công bố chỉ tính trên 3.185 sản phẩm thuộc diện công bố.",
      type: "ratio",
      items: [
        ["GTIN hợp lệ, GCP khớp doanh nghiệp", 5112, 5154],
        ["Hạn sử dụng, bảo quản", 4453, 5154],
        ["Quy cách, đơn vị tính", 4190, 5154],
        ["Phân loại GPC đến Brick", 4542, 5154],
        ["Hình ảnh sản phẩm", 3724, 5154],
        ["Hồ sơ công bố", 2080, 3185],
      ],
    },
    {
      id: "sp2",
      for: ["H1"],
      t: "Tỉ lệ sản phẩm đủ dữ liệu chủ theo phân loại GPC",
      f: "Sản phẩm đủ tất cả trường bắt buộc / Tổng sản phẩm, theo GPC – Segment.",
      type: "bar",
      pct: 1,
      labels: [
        "Sữa",
        "Bánh kẹo",
        "Thủy sản",
        "TP chế biến",
        "Nông sản",
        "Dược liệu",
      ],
      ds: [["Đủ dữ liệu chủ", [91, 72, 63, 57, 49, 38]]],
    },
    {
      id: "sp4",
      for: ["H6", "H7"],
      t: "Sản phẩm khai báo mới và tỉ lệ đủ dữ liệu chủ",
      f: "Cột: sản phẩm doanh nghiệp khai báo mới trong tháng. Đường: Sản phẩm đủ dữ liệu chủ / Tổng sản phẩm tại cuối tháng.",
      type: "combo",
      y2pct: 1,
      labels: ["T4", "T5", "T6", "T7", "T8", "T9"],
      ds: [
        ["Khai báo mới", [180, 210, 236, 251, 240, 262]],
        ["Tỉ lệ đủ dữ liệu chủ (%)", [44, 47, 50, 53, 55, 58], "line"],
      ],
    },
    {
      id: "sp5",
      for: ["H4", "H5"],
      t: "Sản phẩm (GTIN) theo phân loại GPC",
      f: "Đếm sản phẩm theo GPC – Segment doanh nghiệp khai báo; tách đã cấp UID và chưa cấp UID.",
      type: "stack",
      labels: [
        "Thực phẩm chế biến",
        "Nông sản tươi",
        "Thủy sản",
        "Sữa & chế phẩm",
        "Bánh kẹo",
        "Dược liệu",
      ],
      ds: [
        ["Đã cấp UID", [780, 512, 236, 198, 118, 42]],
        ["Chưa cấp UID", [1310, 860, 402, 96, 494, 106]],
      ],
    },
    {
      id: "sp6",
      for: ["H4"],
      t: "Tỉ lệ GTIN đã cấp UID theo phân loại GPC",
      f: "Sản phẩm có ≥ 1 UID / Tổng sản phẩm của GPC – Segment.",
      type: "hbar",
      pct: 1,
      labels: [
        "Sữa & chế phẩm",
        "Thực phẩm chế biến",
        "Nông sản tươi",
        "Thủy sản",
        "Dược liệu",
        "Bánh kẹo",
      ],
      ds: [["Đã cấp UID", [67, 37, 37, 37, 28, 19]]],
    },
    {
      id: "sp7",
      for: ["H1", "H7"],
      t: "Doanh nghiệp chưa hoàn thiện khai báo dữ liệu chủ",
      f: "Số sản phẩm doanh nghiệp chưa khai báo đủ trường bắt buộc, theo doanh nghiệp sở hữu.",
      type: "hbar",
      labels: ["Masan", "TP Hữu Nghị", "Lafooco", "TP Hà Thành", "Tech Brand"],
      ds: [["SP thiếu", [612, 248, 131, 77, 41]]],
    },
    {
      id: "sp8",
      for: ["H1"],
      t: "Tỉ lệ đủ dữ liệu chủ theo phân loại GPC qua các tháng",
      f: "Sản phẩm đủ dữ liệu chủ / Tổng sản phẩm của GPC – Segment, tại cuối mỗi tháng.",
      type: "line",
      y: 1,
      pct: 1,
      labels: ["T4", "T5", "T6", "T7", "T8", "T9"],
      ds: [
        ["Sữa & chế phẩm", [82, 84, 86, 88, 90, 91]],
        ["Thực phẩm chế biến", [41, 44, 48, 51, 54, 57]],
        ["Nông sản tươi", [33, 36, 40, 43, 46, 49]],
      ],
    },
    {
      id: "spW",
      t: "Cầu biến động sản phẩm đủ dữ liệu chủ",
      f: "Đầu kỳ + sản phẩm mới khai báo đủ + sản phẩm được bổ sung đủ − sản phẩm chuyển sang thiếu (trường bắt buộc mới ban hành, sửa làm thiếu) = Cuối kỳ.",
      type: "waterfall",
      for: ["H1"],
      steps: [
        ["Đầu kỳ (31/8)", 2810, "total"],
        ["Mới khai báo đủ", 176],
        ["Bổ sung đủ", 71],
        ["Chuyển sang thiếu", -71],
        ["Cuối kỳ (30/9)", 2986, "total"],
      ],
    },
    {
      id: "spF",
      t: "Phễu sẵn sàng truy xuất của sản phẩm",
      f: "Số sản phẩm đạt từng bước; một sản phẩm ở bước sau đã đạt các bước trước.",
      type: "hbar",
      for: ["H4", "H8"],
      labels: [
        "Đã khai báo",
        "Đã cấp UID",
        "Đã gán quy trình",
        "Có UID đạt đủ công đoạn",
      ],
      ds: [["Sản phẩm", [5154, 1886, 1530, 830]]],
    },
    {
      id: "spG",
      t: "Lỗi GTIN theo loại",
      f: "Số sản phẩm có GTIN không hợp lệ, theo loại lỗi.",
      type: "hbar",
      for: ["H2"],
      labels: [
        "GCP không khớp doanh nghiệp",
        "Sai số kiểm tra",
        "Sai độ dài",
        "Trùng GTIN",
      ],
      ds: [["Sản phẩm", [19, 12, 7, 4]]],
    },
    {
      id: "spC",
      t: "Tỉ lệ có hồ sơ công bố theo phân loại GPC",
      f: "Sản phẩm diện công bố có hồ sơ / Sản phẩm diện công bố, theo GPC – Segment.",
      type: "hbar",
      for: ["H3"],
      pct: 1,
      labels: [
        "Sữa & chế phẩm",
        "Bánh kẹo",
        "Thực phẩm chế biến",
        "Thủy sản",
        "Dược liệu",
      ],
      ds: [["Có hồ sơ", [92, 71, 62, 58, 34]]],
    },
    {
      id: "spN",
      t: "Tỉ lệ đủ dữ liệu chủ của sản phẩm mới theo đơn vị cung cấp giải pháp",
      f: "Sản phẩm mới khai báo đủ ngay khi tạo / Sản phẩm mới, theo đơn vị doanh nghiệp ủy quyền.",
      type: "hbar",
      for: ["H7"],
      pct: 1,
      labels: [
        "Checkee",
        "TrangNTT",
        "ThanhTP",
        "Test Đại Lý 01",
        "Tự khai báo",
      ],
      ds: [["Đủ khi tạo", [86, 74, 66, 52, 61]]],
    },
  ],
  warns: [
    {
      for: ["H1", "H7"],
      t: "Sản phẩm chưa đủ dữ liệu chủ",
      sev: "high",
      n: 2168,
      cols: [
        "Sản phẩm",
        "Mã GTIN",
        "Tổ chức, cá nhân sở hữu",
        "Trường chưa khai báo",
        "DN cập nhật cuối",
      ],
      rows: [
        [
          "Nạc dăm heo (F)",
          "8935315900078",
          "Masan",
          "Hình ảnh, Hạn sử dụng",
          "14/08/2026",
        ],
        [
          "Giò sống",
          "8935350700008",
          "Masan",
          "Hình ảnh, Quy cách",
          "14/08/2026",
        ],
        [
          "Nem chua rán",
          "8935350700015",
          "Masan",
          "Hình ảnh, Hồ sơ công bố",
          "02/09/2026",
        ],
        [
          "Sản phẩm dữ liệu dạng File",
          "8938660328016",
          "[TEST]",
          "GPC – Brick, Quy cách",
          "10/09/2026",
        ],
      ],
    },
    {
      for: ["H2"],
      t: "GTIN doanh nghiệp khai báo không hợp lệ hoặc GCP không khớp",
      sev: "critical",
      n: 42,
      cols: ["Sản phẩm", "Mã GTIN", "Lỗi", "Tổ chức, cá nhân sở hữu"],
      rows: [
        ["Bánh cracker ngũ cốc", "893866032801", "Thiếu 1 chữ số", "[TEST]"],
        [
          "Trà ô long túi lọc",
          "8934563210019",
          "Sai số kiểm tra",
          "Cty Chè Tân Cương",
        ],
        [
          "Nước mắm Cửu Long",
          "8938501234567",
          "GCP thuộc DN khác",
          "Thủy sản Cửu Long",
        ],
      ],
    },
    {
      for: ["H3"],
      t: "Sản phẩm thuộc diện công bố chưa có hồ sơ công bố",
      sev: "critical",
      n: 1105,
      cols: ["Sản phẩm", "Phân loại GPC", "Doanh nghiệp", "Có UID"],
      rows: [
        ["Nem chua rán", "Thực phẩm chế biến", "Masan", "Có"],
        ["Sữa chua uống men sống", "Sữa & chế phẩm", "Cty CP Sữa Ba Vì", "Có"],
        ["Bánh quy bơ Pháp", "Bánh kẹo", "[TEST]", "Có"],
        ["Chả cá Lã Vọng", "Thủy sản", "Cty TP Hà Thành", "Không"],
      ],
    },
    {
      for: ["H8"],
      t: "Sản phẩm đã cấp UID nhưng chưa gán quy trình tiêu chuẩn TXNG",
      sev: "high",
      n: 356,
      cols: ["Sản phẩm", "Mã GTIN", "Tổ chức, cá nhân sở hữu", "Số UID"],
      rows: [
        ["Ba rọi heo không da (F)", "8935315900030", "Masan", 1240],
        ["Gạo ST25 túi 5kg", "8936012345671", "HTX Phước An", 860],
        ["Tôm thẻ đông lạnh", "8938765432109", "Thủy sản Cửu Long", 412],
      ],
    },
  ],
};
