import type { Mod } from "../types";

/** Tích hợp hệ thống › Sự kiện tích hợp (/tich-hop/webhook) */
export const suKienTichHop: Mod = {
  k: "wh",
  g: "Tích hợp hệ thống",
  t: "Sự kiện tích hợp",
  d: "Sự kiện nhận qua API, webhook từ đơn vị cung cấp giải pháp và hệ thống liên thông",
  href: "/tich-hop/webhook",
  cards: [
    {
      id: "H1",
      l: "Tỉ lệ sự kiện tích hợp thành công",
      v: 482310,
      t: 0.6,
      k: "core",
      d: 496420,
      f: "Sự kiện xử lý thành công / Tổng sự kiện nhận.",
    },
    {
      id: "H2",
      l: "Tỉ lệ webhook gửi thành công lần đầu",
      v: 96820,
      t: 1.1,
      k: "core",
      d: 101340,
      f: "Webhook phản hồi 2xx ở lần gửi đầu / Tổng webhook gửi.",
    },
    {
      id: "H3",
      l: "Tỉ lệ endpoint hoạt động ổn định",
      v: 41,
      t: 2.5,
      k: "core",
      d: 46,
      f: "Endpoint có tỉ lệ lỗi < 2% trong 7 ngày / Tổng endpoint đăng ký.",
    },
    {
      id: "H4",
      l: "Tỉ lệ sự kiện xử lý dưới 5 giây",
      v: 468900,
      t: 0.9,
      k: "core",
      d: 496420,
      f: "Sự kiện có thời gian xử lý < 5 giây / Tổng sự kiện nhận.",
    },
    { id: "H5", l: "Sự kiện nhận trong tháng", v: 496420, t: 12.8, k: "scale" },
    { id: "H6", l: "Endpoint đăng ký", v: 46, t: 4.5, k: "scale" },
    {
      id: "H7",
      l: "Sự kiện lỗi chờ xử lý lại",
      v: 3842,
      t: -11.2,
      k: "risk",
      bad: 1,
    },
    {
      id: "H8",
      l: "Endpoint lỗi liên tục quá 24 giờ",
      v: 2,
      t: 0,
      k: "risk",
      bad: 1,
    },
  ],
  charts: [
    {
      id: "wh1",
      for: ["H1", "H5"],
      t: "Sự kiện tích hợp theo tháng",
      f: "Cột: sự kiện nhận (nghìn). Đường: tỉ lệ thành công.",
      type: "combo",
      y2pct: 1,
      y2free: 1,
      labels: ["T4", "T5", "T6", "T7", "T8", "T9"],
      ds: [
        ["Sự kiện (nghìn)", [312, 348, 381, 412, 440, 496]],
        ["Thành công (%)", [95.1, 95.8, 96.4, 96.9, 96.8, 97.2], "line"],
      ],
    },
    {
      id: "wh2",
      for: ["H7"],
      t: "Nguyên nhân lỗi tích hợp",
      f: "Đếm sự kiện lỗi trong tháng theo mã lỗi.",
      type: "pie",
      labels: [
        "Sai định dạng dữ liệu",
        "Thiếu trường bắt buộc",
        "Mã GTIN/GLN không tồn tại",
        "Hết thời gian chờ",
        "Xác thực thất bại",
      ],
      ds: [["Sự kiện lỗi", [4210, 3120, 2860, 2104, 1816]]],
    },
    {
      id: "wh3",
      for: ["H3"],
      t: "Tỉ lệ thành công theo đơn vị cung cấp giải pháp",
      f: "Sự kiện thành công / Sự kiện nhận từ đơn vị.",
      type: "hbar",
      pct: 1,
      labels: ["Checkee", "TrangNTT", "ThanhTP", "Test Đại Lý 01", "P6_Thanh"],
      ds: [["Thành công", [99.1, 98.2, 96.7, 93.4, 88.6]]],
    },
  ],
  warns: [
    {
      t: "Endpoint lỗi liên tục quá 24 giờ",
      sev: "critical",
      n: 2,
      cols: ["Endpoint", "Đơn vị", "Mã lỗi", "Lỗi từ"],
      rows: [
        ["/hooks/p6-thanh/events", "P6_Thanh", "503", "29/09/2026 22:14"],
        ["/hooks/daily01/scan", "Test Đại Lý 01", "401", "30/09/2026 03:40"],
      ],
      for: ["H3", "H8"],
    },
    {
      t: "Đơn vị có tỉ lệ lỗi tích hợp trên 5%",
      sev: "high",
      n: 2,
      cols: ["Đơn vị", "Sự kiện", "Lỗi", "Tỉ lệ"],
      rows: [
        ["P6_Thanh", 21480, 2446, "11,4%"],
        ["Test Đại Lý 01", 18210, 1202, "6,6%"],
      ],
      for: ["H1", "H7"],
    },
  ],
};
