import type { Mod } from "../types";

/** Danh mục hệ thống › Thư viện mẫu sự kiện (/danh-muc/thu-vien-mau-su-kien) */
export const thuVienMauSuKien: Mod = {
  k: "tvmsk",
  g: "Danh mục hệ thống",
  t: "Thư viện mẫu sự kiện",
  d: "Thư viện mẫu sự kiện truy xuất dùng chung cho các quy trình tiêu chuẩn",
  href: "/danh-muc/thu-vien-mau-su-kien",
  cards: [
    {
      id: "H1",
      l: "Tỉ lệ mẫu đang được dùng trong quy trình",
      v: 48,
      t: 4.3,
      k: "core",
      d: 57,
      f: "Mẫu sự kiện thuộc ≥ 1 quy trình tiêu chuẩn TXNG đang áp dụng / Tổng mẫu.",
    },
    {
      id: "H2",
      l: "Tỉ lệ mẫu ánh xạ loại sự kiện GS1 EPCIS",
      v: 53,
      t: 1.9,
      k: "core",
      d: 57,
      f: "Mẫu có ánh xạ ObjectEvent, TransformationEvent… / Tổng mẫu.",
    },
    {
      id: "H3",
      l: "Tỉ lệ mẫu có phiên bản hiện hành được duyệt",
      v: 51,
      t: 2,
      k: "core",
      d: 57,
      f: "Mẫu có phiên bản đã phê duyệt / Tổng mẫu.",
    },
    {
      id: "H4",
      l: "Tỉ lệ sự kiện khai báo hợp lệ theo mẫu",
      v: 94.1,
      t: 1.2,
      k: "core",
      d: 100,
      f: "Sự kiện qua kiểm tra theo mẫu / Tổng sự kiện khai báo trong tháng (%).",
    },
    { id: "H5", l: "Tổng số mẫu sự kiện", v: 57, t: 3.6, k: "scale" },
    { id: "H6", l: "Phiên bản mới trong tháng", v: 6, t: 20, k: "scale" },
    {
      id: "H7",
      l: "Mẫu chờ phê duyệt quá 14 ngày",
      v: 3,
      t: 50,
      k: "risk",
      bad: 1,
    },
    {
      id: "H8",
      l: "Mẫu không dùng quá 180 ngày",
      v: 7,
      t: 0,
      k: "risk",
      bad: 1,
    },
  ],
  charts: [
    {
      id: "tv1",
      for: ["H5"],
      t: "Mẫu sự kiện theo công đoạn",
      f: "Đếm mẫu theo công đoạn trong chuỗi cung ứng.",
      type: "bar",
      labels: [
        "Nuôi trồng",
        "Thu hoạch",
        "Sản xuất, chế biến",
        "Đóng gói",
        "Vận chuyển",
        "Phân phối, bán lẻ",
      ],
      ds: [["Mẫu", [9, 7, 14, 8, 10, 9]]],
    },
    {
      id: "tv2",
      for: ["H4"],
      t: "Mẫu có tỉ lệ khai báo lỗi cao nhất",
      f: "Sự kiện không qua kiểm tra / Sự kiện khai báo theo mẫu, trong tháng.",
      type: "hbar",
      pct: 1,
      labels: [
        "Tiếp nhận nguyên liệu",
        "Xuất hàng",
        "Chế biến",
        "Đóng gói",
        "Thu hoạch",
      ],
      ds: [["Lỗi", [11.4, 9.2, 7.1, 5.3, 4.8]]],
    },
  ],
  warns: [
    {
      t: "Mẫu sự kiện chờ phê duyệt phiên bản quá 14 ngày",
      sev: "medium",
      n: 3,
      cols: ["Mẫu", "Phiên bản", "Người gửi", "Ngày gửi"],
      rows: [
        ["Xuất hàng thủy sản", "v3.1", "Bộ NN&MT", "08/09/2026"],
        ["Tiếp nhận sữa tươi", "v2.0", "Bộ Công Thương", "11/09/2026"],
      ],
      for: ["H3", "H7"],
    },
  ],
};
