import type { Mod } from "../types";

/** Danh mục hệ thống › Trường dữ liệu (/danh-muc/thu-vien-kde) */
export const truongDuLieu: Mod = {
  k: "kde",
  g: "Danh mục hệ thống",
  t: "Trường dữ liệu",
  d: "Thư viện trường dữ liệu chuẩn (KDE – Key Data Element) dùng trong mẫu sự kiện truy xuất",
  href: "/danh-muc/thu-vien-kde",
  cards: [
    {
      id: "H1",
      l: "Tỉ lệ trường dữ liệu đang được sử dụng",
      v: 142,
      t: 3.6,
      k: "core",
      d: 168,
      f: "Trường dữ liệu được dùng trong ≥ 1 mẫu sự kiện đang áp dụng / Tổng trường dữ liệu.",
    },
    {
      id: "H2",
      l: "Tỉ lệ trường có quy tắc kiểm tra dữ liệu",
      v: 128,
      t: 6.7,
      k: "core",
      d: 168,
      f: "Trường có định nghĩa kiểu, định dạng, ràng buộc / Tổng trường.",
    },
    {
      id: "H3",
      l: "Tỉ lệ trường ánh xạ chuẩn GS1 EPCIS",
      v: 117,
      t: 2.6,
      k: "core",
      d: 168,
      f: "Trường có ánh xạ sang thuộc tính GS1 EPCIS (chuẩn sự kiện truy xuất) / Tổng trường.",
    },
    {
      id: "H4",
      l: "Tỉ lệ giá trị khai báo hợp lệ",
      v: 96.4,
      t: 0.8,
      k: "core",
      d: 100,
      f: "Giá trị khai báo qua quy tắc kiểm tra / Tổng giá trị khai báo trong tháng (%).",
    },
    { id: "H5", l: "Tổng số trường dữ liệu", v: 168, t: 4.3, k: "scale" },
    { id: "H6", l: "Phiên bản mới trong tháng", v: 11, t: 37.5, k: "scale" },
    {
      id: "H7",
      l: "Trường trùng nghĩa cần hợp nhất",
      v: 9,
      t: -10,
      k: "risk",
      bad: 1,
    },
    {
      id: "H8",
      l: "Trường không dùng quá 180 ngày",
      v: 26,
      t: 4,
      k: "risk",
      bad: 1,
    },
  ],
  charts: [
    {
      id: "kde1",
      for: ["H1", "H2", "H3"],
      t: "Chất lượng thư viện trường dữ liệu",
      f: "Trường đạt tiêu chí / Tổng trường (168).",
      type: "ratio",
      items: [
        ["Đang được sử dụng", 142, 168],
        ["Có quy tắc kiểm tra", 128, 168],
        ["Ánh xạ chuẩn GS1 EPCIS", 117, 168],
        ["Có mô tả, ví dụ", 151, 168],
      ],
    },
    {
      id: "kde2",
      for: ["H5"],
      t: "Trường dữ liệu theo nhóm thông tin",
      f: "Đếm trường theo nhóm thông tin.",
      type: "pie",
      labels: [
        "Sản phẩm",
        "Lô, số lượng",
        "Địa điểm",
        "Thời gian",
        "Chứng nhận",
        "Khác",
      ],
      ds: [["Trường", [42, 31, 28, 19, 24, 24]]],
    },
    {
      id: "kde3",
      for: ["H4"],
      t: "Trường có tỉ lệ khai báo lỗi cao nhất",
      f: "Giá trị không qua quy tắc kiểm tra / Giá trị khai báo của trường, trong tháng.",
      type: "hbar",
      pct: 1,
      labels: [
        "Ngày hết hạn",
        "Mã GLN cơ sở",
        "Số lượng, đơn vị tính",
        "Mã lô",
        "Nhiệt độ bảo quản",
      ],
      ds: [["Lỗi", [8.2, 6.1, 4.7, 3.9, 3.1]]],
    },
  ],
  warns: [
    {
      t: "Trường dữ liệu trùng nghĩa giữa các mẫu sự kiện",
      sev: "high",
      n: 9,
      cols: ["Trường", "Trùng với", "Số mẫu dùng", "Đề xuất"],
      rows: [
        ["ngay_san_xuat", "production_date", 14, "Hợp nhất"],
        ["ma_lo", "batch_no", 11, "Hợp nhất"],
      ],
      for: ["H7"],
    },
    {
      t: "Trường đang dùng nhưng chưa có quy tắc kiểm tra",
      sev: "medium",
      n: 21,
      cols: ["Trường", "Nhóm", "Số mẫu dùng", "Kiểu dữ liệu"],
      rows: [
        ["nhiet_do_bao_quan", "Sản phẩm", 6, "Văn bản"],
        ["vung_trong", "Địa điểm", 4, "Văn bản"],
      ],
      for: ["H2"],
    },
  ],
};
