import type { Mod } from "../types";

/** Quản lý ATTP › Truyền thông ATTP (/truyen-thong/chien-dich) */
export const truyenThongAttp: Mod = {
  k: "tt",
  g: "Quản lý ATTP",
  t: "Truyền thông ATTP",
  d: "Chiến dịch, hoạt động truyền thông và tập huấn kiến thức an toàn thực phẩm",
  href: "/truyen-thong/chien-dich",
  cards: [
    {
      id: "H1",
      l: "Tỉ lệ chiến dịch hoàn thành đúng hạn",
      v: 18,
      t: 6,
      k: "core",
      d: 22,
      f: "Chiến dịch kết thúc đúng thời gian kế hoạch / Chiến dịch đã kết thúc.",
    },
    {
      id: "H2",
      l: "Tỉ lệ người được tập huấn đạt kiểm tra",
      v: 3412,
      t: 2.7,
      k: "core",
      d: 3880,
      f: "Người đạt bài kiểm tra kiến thức ATTP / Người tham gia tập huấn.",
    },
    {
      id: "H3",
      l: "Tỉ lệ xã, phường có hoạt động truyền thông",
      v: 286,
      t: 4.1,
      k: "core",
      d: 412,
      f: "Xã, phường có ≥ 1 hoạt động truyền thông trong quý / Tổng xã, phường thuộc phạm vi.",
    },
    {
      id: "H4",
      l: "Tỉ lệ tiếp cận mục tiêu",
      v: 1.42,
      t: 9,
      k: "core",
      d: 2,
      f: "Lượt tiếp cận thực tế (triệu) / Chỉ tiêu tiếp cận năm (triệu).",
    },
    { id: "H5", l: "Chiến dịch đang triển khai", v: 9, t: 12.5, k: "scale" },
    { id: "H6", l: "Hoạt động trong tháng", v: 146, t: 8.1, k: "scale" },
    {
      id: "H7",
      l: "Chiến dịch chưa có báo cáo kết quả",
      v: 4,
      t: 33.3,
      k: "risk",
      bad: 1,
    },
    {
      id: "H8",
      l: "Xã, phường chưa có hoạt động 2 quý",
      v: 57,
      t: -5,
      k: "risk",
      bad: 1,
    },
  ],
  charts: [
    {
      id: "tt1",
      for: ["H4"],
      t: "Lượt tiếp cận theo kênh",
      f: "Lượt tiếp cận lũy kế năm theo kênh truyền thông (nghìn lượt).",
      type: "hbar",
      labels: [
        "Mạng xã hội",
        "Truyền hình, phát thanh",
        "Loa truyền thanh cơ sở",
        "Tờ rơi, áp phích",
        "Hội nghị, tập huấn",
      ],
      ds: [["Nghìn lượt", [612, 384, 236, 118, 70]]],
    },
    {
      id: "tt2",
      for: ["H5", "H6"],
      t: "Hoạt động truyền thông theo tháng",
      f: "Số hoạt động tổ chức trong tháng, tách theo loại.",
      type: "stack",
      labels: ["T4", "T5", "T6", "T7", "T8", "T9"],
      ds: [
        ["Tập huấn", [22, 26, 31, 28, 34, 38]],
        ["Sự kiện, hội nghị", [14, 18, 21, 16, 19, 24]],
        ["Ấn phẩm, bài viết", [61, 64, 70, 72, 79, 84]],
      ],
    },
    {
      id: "tt3",
      for: ["H2"],
      t: "Tỉ lệ đạt kiểm tra kiến thức theo đối tượng",
      f: "Người đạt / Người được tập huấn, theo đối tượng.",
      type: "hbar",
      pct: 1,
      labels: [
        "Chủ cơ sở sản xuất",
        "Người chế biến",
        "Bếp ăn tập thể",
        "Thức ăn đường phố",
        "Người tiêu dùng",
      ],
      ds: [["Đạt", [93, 89, 87, 78, 84]]],
    },
    {
      id: "tt4",
      for: ["H3", "H8"],
      t: "Độ phủ hoạt động theo địa phương",
      f: "Xã, phường có hoạt động trong quý / Tổng xã, phường của tỉnh.",
      type: "bar",
      pct: 1,
      labels: ["Hà Nội", "TP.HCM", "Đà Nẵng", "Lâm Đồng", "Long An", "Cần Thơ"],
      ds: [["Độ phủ", [84, 76, 72, 61, 58, 55]]],
    },
  ],
  warns: [
    {
      t: "Chiến dịch kết thúc quá 15 ngày chưa nộp báo cáo kết quả",
      sev: "high",
      n: 4,
      cols: ["Chiến dịch", "Đơn vị chủ trì", "Ngày kết thúc", "Quá hạn (ngày)"],
      rows: [
        ["Tháng hành động vì ATTP 2026", "Sở Y tế Long An", "31/05/2026", 114],
        ["Tết Trung thu an toàn", "Chi cục ATVSTP Cần Thơ", "10/09/2026", 12],
      ],
      for: ["H1", "H7"],
    },
    {
      t: "Xã, phường không có hoạt động truyền thông 2 quý liên tiếp",
      sev: "medium",
      n: 57,
      cols: [
        "Xã, phường",
        "Tỉnh/thành",
        "Hoạt động gần nhất",
        "Số cơ sở trên địa bàn",
      ],
      rows: [
        ["Xã Tân Thạnh", "Long An", "14/02/2026", 38],
        ["Phường Ninh Kiều", "Cần Thơ", "03/03/2026", 112],
        ["Xã Đạ Huoai", "Lâm Đồng", "20/01/2026", 21],
      ],
      for: ["H3", "H8"],
    },
  ],
};
