import type { Mod } from "../types";

/** Quản trị hệ thống › Vai trò (/quan-tri/vai-tro) */
export const vaiTro: Mod = {
  k: "vaitro",
  g: "Quản trị hệ thống",
  t: "Vai trò",
  d: "Vai trò và phân quyền truy cập chức năng, dữ liệu",
  href: "/quan-tri/vai-tro",
  cards: [
    {
      id: "H1",
      l: "Tỉ lệ vai trò đang được sử dụng",
      v: 21,
      t: 0,
      k: "core",
      d: 26,
      f: "Vai trò có ≥ 1 tài khoản / Tổng vai trò.",
    },
    {
      id: "H2",
      l: "Tỉ lệ vai trò tuân thủ đặc quyền tối thiểu",
      v: 22,
      t: 4.8,
      k: "core",
      d: 26,
      f: "Vai trò không có quyền vượt phạm vi đơn vị / Tổng vai trò.",
    },
    {
      id: "H3",
      l: "Tỉ lệ vai trò được rà soát trong 6 tháng",
      v: 17,
      t: 13.3,
      k: "core",
      d: 26,
      f: "Vai trò được rà soát quyền trong 6 tháng / Tổng vai trò.",
    },
    {
      id: "H4",
      l: "Tỉ lệ tài khoản chỉ có 1 vai trò",
      v: 1488,
      t: 1.1,
      k: "core",
      d: 1651,
      f: "Tài khoản có đúng 1 vai trò / Tài khoản đã gán vai trò.",
    },
    { id: "H5", l: "Tổng số vai trò", v: 26, t: 4, k: "scale" },
    {
      id: "H6",
      l: "Quyền chức năng được cấu hình",
      v: 184,
      t: 2.2,
      k: "scale",
    },
    {
      id: "H7",
      l: "Vai trò có quyền xóa dữ liệu",
      v: 6,
      t: 20,
      k: "risk",
      bad: 1,
    },
    {
      id: "H8",
      l: "Vai trò không được dùng quá 90 ngày",
      v: 5,
      t: 0,
      k: "risk",
      bad: 1,
    },
  ],
  charts: [
    {
      id: "vt1",
      for: ["H4", "H5"],
      t: "Số tài khoản theo vai trò",
      f: "Đếm tài khoản đang kích hoạt theo vai trò; 6 vai trò nhiều nhất.",
      type: "hbar",
      labels: [
        "Doanh nghiệp – Quản trị",
        "Doanh nghiệp – Nhập liệu",
        "Cán bộ thanh tra",
        "Cán bộ quản lý cấp xã",
        "Đơn vị giải pháp",
        "Lãnh đạo Sở",
      ],
      ds: [["Tài khoản", [612, 488, 164, 142, 112, 38]]],
    },
    {
      id: "vt2",
      for: ["H2", "H7"],
      t: "Vai trò theo mức đặc quyền",
      f: "Phân loại vai trò theo quyền cao nhất được cấp.",
      type: "pie",
      labels: [
        "Chỉ xem",
        "Xem và nhập liệu",
        "Phê duyệt",
        "Quản trị, xóa dữ liệu",
      ],
      ds: [["Vai trò", [7, 9, 4, 6]]],
    },
    {
      id: "vt3",
      for: ["H1", "H3"],
      t: "Tình trạng quản lý vai trò",
      f: "Vai trò đạt tiêu chí / Tổng vai trò (26).",
      type: "ratio",
      items: [
        ["Đang được sử dụng", 21, 26],
        ["Tuân thủ đặc quyền tối thiểu", 22, 26],
        ["Rà soát trong 6 tháng", 17, 26],
      ],
    },
  ],
  warns: [
    {
      t: "Vai trò có quyền xóa dữ liệu gán cho tài khoản ngoài đơn vị quản trị",
      sev: "high",
      n: 2,
      cols: ["Vai trò", "Tài khoản", "Đơn vị", "Ngày gán"],
      rows: [
        ["Quản trị danh mục", "cb.qlnn05", "Sở Y tế Cần Thơ", "14/08/2026"],
        ["Quản trị doanh nghiệp", "dt.trangntt", "TrangNTT", "02/09/2026"],
      ],
      for: ["H2", "H7"],
    },
    {
      t: "Vai trò chưa rà soát quyền quá 6 tháng",
      sev: "medium",
      n: 9,
      cols: ["Vai trò", "Số tài khoản", "Rà soát gần nhất", "Người tạo"],
      rows: [
        ["Cán bộ quản lý cấp xã", 142, "10/01/2026", "admin"],
        ["Đơn vị giải pháp", 112, "22/02/2026", "admin"],
      ],
      for: ["H3"],
    },
  ],
};
